/**
 * Builds a printable HTML "design report" — apartment name, per-room areas +
 * total, a furniture shopping list with an approximate budget, and a hero
 * render. Opened in a new window so the user can print / save as PDF.
 */
import type { FloorPlan } from '../floorplan/types';
import { planRoomArea, planTotalArea } from '../floorplan/types';
import { itemPrice } from '../furniture/furniturePrices';
import type { FurnitureDef, FurnitureItem, FurnitureCategory } from '../furniture/types';
import { FURNITURE_CATEGORIES } from '../furniture/types';

const CAT_LABEL: Record<FurnitureCategory, string> = {
  beds: 'Beds', seating: 'Seating', tables: 'Tables', storage: 'Storage',
  kitchen: 'Kitchen', bathroom: 'Bathroom', appliances: 'Appliances',
  lighting: 'Lighting', decor: 'Decor', textiles: 'Textiles', outdoor: 'Outdoor',
};

const esc = (s: string) => s.replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]!));
const sgd = (n: number) => `$${Math.round(n).toLocaleString('en-SG')}`;

export function buildReportHtml(
  plan: FloorPlan,
  items: FurnitureItem[],
  catalog: Record<string, FurnitureDef>,
  heroDataUrl: string | null,
): string {
  // Rooms (skip external ledges with ~0 interior use are still listed).
  const roomRows = plan.rooms
    .map((r) => `<tr><td>${esc(r.name)}</td><td class="num">${planRoomArea(r).toFixed(1)} m²</td></tr>`)
    .join('');
  const totalArea = planTotalArea(plan);

  // Furniture grouped by category.
  const byCat = new Map<FurnitureCategory, Map<string, { name: string; count: number; each: number }>>();
  let budget = 0;
  for (const it of items) {
    const def = catalog[it.defId];
    if (!def) continue;
    const each = itemPrice(def, def.category);
    budget += each;
    if (!byCat.has(def.category)) byCat.set(def.category, new Map());
    const m = byCat.get(def.category)!;
    const ex = m.get(it.defId);
    if (ex) ex.count += 1;
    else m.set(it.defId, { name: def.name, count: 1, each });
  }
  const furnitureRows = FURNITURE_CATEGORIES.filter((c) => byCat.has(c))
    .map((c) => {
      const lines = [...byCat.get(c)!.values()].sort((a, b) => b.each * b.count - a.each * a.count);
      const sub = lines.reduce((s, l) => s + l.each * l.count, 0);
      return (
        `<tr class="cat"><td>${CAT_LABEL[c]}</td><td class="num">${sgd(sub)}</td></tr>` +
        lines
          .map((l) => `<tr><td class="indent">${esc(l.name)}${l.count > 1 ? ` ×${l.count}` : ''}</td><td class="num">${sgd(l.each * l.count)}</td></tr>`)
          .join('')
      );
    })
    .join('');

  const hero = heroDataUrl ? `<img class="hero" src="${heroDataUrl}" alt="render"/>` : '';
  const date = new Date().toLocaleDateString('en-SG', { year: 'numeric', month: 'long', day: 'numeric' });

  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(plan.name)} — Design Report</title>
<style>
  * { box-sizing: border-box; }
  body { font: 13px/1.5 -apple-system, Segoe UI, Roboto, sans-serif; color: #1f2937; margin: 0; padding: 32px; }
  h1 { font-size: 22px; margin: 0 0 2px; }
  .sub { color: #6b7280; margin-bottom: 18px; }
  .hero { width: 100%; max-height: 360px; object-fit: cover; border-radius: 8px; margin-bottom: 20px; border: 1px solid #e5e7eb; }
  .cols { display: flex; gap: 28px; align-items: flex-start; }
  .col { flex: 1; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: .05em; color: #6b7280; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 2px 0; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; color: #374151; }
  tr.cat td { font-weight: 600; padding-top: 8px; }
  td.indent { padding-left: 12px; color: #4b5563; }
  .total { display: flex; justify-content: space-between; font-weight: 700; font-size: 15px; border-top: 2px solid #1f2937; margin-top: 8px; padding-top: 6px; }
  .foot { margin-top: 24px; color: #9ca3af; font-size: 11px; }
  @media print { body { padding: 0; } .hero { max-height: 300px; } }
</style></head>
<body>
  <h1>${esc(plan.name)}</h1>
  <div class="sub">Interior design report · ${date} · ${items.length} furniture pieces</div>
  ${hero}
  <div class="cols">
    <div class="col">
      <h2>Rooms &amp; areas</h2>
      <table>${roomRows}</table>
      <div class="total"><span>Total interior</span><span>${totalArea.toFixed(1)} m²</span></div>
    </div>
    <div class="col">
      <h2>Furniture &amp; budget</h2>
      <table>${furnitureRows || '<tr><td>No furniture placed.</td></tr>'}</table>
      <div class="total"><span>Estimated total</span><span>${sgd(budget)}</span></div>
    </div>
  </div>
  <div class="foot">Areas are interior floor area. Costs are an approximate mid-market retail estimate (SGD); finishes, renovation and labour are not included. Generated by the HDB design sandbox.</div>
</body></html>`;
}
