// AUTO-GENERATED by scripts/asset-pipeline/index-assets.ts. Do not edit.
import type { FurnitureDef } from './types';

export const GENERATED_FURNITURE: FurnitureDef[] = [
  {
    kind: 'gltf',
    id: "demo-box",
    name: "Demo box",
    category: "decor",
    source: 'builtin',
    url: "/assets/furniture/demo-box.glb",
    license: 'CC0',
    attribution: "Khronos glTF Sample Models",
    sourceUrl: "https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/Box",
    defaultFootprint: { w: 1, d: 1, h: 1 },
    scale: 0.6,
  },
  {
    kind: 'gltf',
    id: "demo-duck",
    name: "Demo duck",
    category: "decor",
    source: 'builtin',
    url: "/assets/furniture/demo-duck.glb",
    license: 'CC0',
    attribution: "Khronos glTF Sample Models",
    sourceUrl: "https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/Duck",
    defaultFootprint: { w: 0.6, d: 0.6, h: 1 },
    scale: 0.005,
  },
];
