/**
 * AI design chat (v1, read-only, BYO-key) — a concise interior-design advisor
 * for Singapore HDB/condo homes, grounded in the LIVE design's own computed
 * numbers via `buildDesignChatContext`. No write access: this module only
 * asks a question and returns the model's reply text; it never mutates the
 * store or proposes an "apply" action.
 *
 * Reuses the SAME BYO key/endpoint (`hdb_ai_vision_*`) and the SAME
 * `classifyVisionEndpoint` security gate as `floorPlanAi.ts`/
 * `floorPlanGenerate.ts` — one BYO credential for all AI features (per that
 * precedent), so a user who's already set up AI plan generation/recognition
 * doesn't need a second key.
 */
import {
  AiPlanError,
  classifyVisionEndpoint,
  extractContent,
  getVisionKey,
  getVisionModel,
  getVisionUrl,
} from './floorPlanAi'

/** A single turn in the chat history. */
export interface DesignChatMessage {
  role: 'user' | 'assistant'
  content: string
}

/** Rolling history cap — keep the request small; the context string itself
 *  already carries the grounding, so the model doesn't need a long transcript
 *  to stay on-topic. */
export const MAX_HISTORY_TURNS = 10

const SYSTEM_PROMPT = `You are a concise interior-design advisor for Singapore HDB flats and condominiums.

You are given a DESIGN SUMMARY block below, generated by the app from the user's ACTUAL live \
design (real room dimensions, real placed furniture with positions, and the app's own computed \
quality scores). Hard rules — follow ALL of them:
1. ONLY cite numbers, room names, item names, and positions that appear in the DESIGN SUMMARY. \
Never estimate, guess, or invent a dimension, distance, area, or score yourself.
2. If the user asks about something the DESIGN SUMMARY does not cover (it explicitly lists what \
is NOT AVAILABLE), reply that you can't measure that from here — do not fabricate an answer.
3. Be concise and practical: a few sentences or a short bullet list, not an essay.
4. You have READ-ONLY advice access — you cannot move, add, or edit anything. Suggest changes in \
words; never claim to have made an edit.
5. Ground advice in Singapore HDB/condo norms (compact rooms, void deck/corridor constraints, \
tropical daylight/ventilation, common furniture scales) where relevant.`

/** Build the OpenAI-compatible chat request. Pure — no network, no key (the
 *  caller attaches the bearer). `history` is capped to the most recent
 *  `MAX_HISTORY_TURNS` turns before the new user message is appended. */
export function buildDesignChatRequest(
  contextText: string,
  question: string,
  history: DesignChatMessage[] = [],
  model = getVisionModel(),
) {
  const cappedHistory = history.slice(-MAX_HISTORY_TURNS)
  return {
    model,
    max_tokens: 700,
    messages: [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'system', content: contextText },
      ...cappedHistory.map((m) => ({ role: m.role, content: m.content })),
      { role: 'user', content: question },
    ],
  }
}

/**
 * Ask the design-chat advisor a question, grounded in `contextText` (from
 * `buildDesignChatContext`). Returns the assistant's reply text. Throws
 * `AiPlanError` with a user-facing message on a missing key, an insecure
 * endpoint, a network failure (often CORS), or a provider error.
 */
export async function askDesignChat(
  contextText: string,
  question: string,
  history: DesignChatMessage[] = [],
  { key = getVisionKey(), url = getVisionUrl(), model = getVisionModel() } = {},
): Promise<string> {
  const trimmed = question.trim()
  if (!trimmed) throw new AiPlanError('Ask a question first.')
  if (!key) throw new AiPlanError('Add an LLM API key first.')
  // Never POST the bearer key over an insecure transport — mirrors the vision
  // + plan-generation paths.
  const check = classifyVisionEndpoint(url)
  if (!check.secure) throw new AiPlanError(check.reason ?? 'Insecure AI endpoint.')
  let res: Response
  try {
    res = await fetch(url, {
      method: 'POST',
      headers: { authorization: `Bearer ${key}`, 'content-type': 'application/json' },
      body: JSON.stringify(buildDesignChatRequest(contextText, trimmed, history, model)),
    })
  } catch {
    throw new AiPlanError('Could not reach the AI provider (often CORS). A local proxy may help.')
  }
  if (res.status === 401) throw new AiPlanError('Invalid API key.')
  if (!res.ok) throw new AiPlanError(`Provider error (${res.status}).`)
  const reply = extractContent(await res.json())
  if (!reply.trim()) throw new AiPlanError('The model returned an empty reply — try again.')
  return reply
}
