/**
 * Lightmap UVs for the room shell — the `uv1` channel a baked `aoMap` is sampled through.
 *
 * **Why a second channel exists at all.** The shell meshes' primary UVs are *tiling*
 * coordinates in metres, so repeating plaster and tile textures work: measured on a real
 * export they run u = −2.9…+2.9, v = −1.6…+1.0. A baked texture lives in 0…1, so baking into
 * that channel writes most of the surface outside the image — `v0.31.7.11` measured exactly
 * that, `min 0.0, max 0.0` on the two largest walls. three also samples `aoMap` through `uv1`
 * rather than `uv`, so a separate channel is required regardless.
 *
 * **Why this is generated rather than shipped.** The layout is a 3×2 box atlas whose every
 * input is *local* geometry — the dominant axis and sign of a face's normal pick the slot, and
 * the face's two remaining object-space coordinates, normalised by the mesh's own bounding box,
 * place it inside that slot. Nothing depends on packing order, mesh identity or bake order, so
 * the runtime reproduces Blender's layout exactly without shipping a UV table alongside every
 * map. A `smart_project` unwrap packs more tidily and could not offer that.
 *
 * This is the deliberate twin of `python/scripts/blender/bake_material.py:make_box_uvs`, and
 * `lightmapUv.test.ts` holds the two to a fixture generated by Blender itself — the pair is only
 * useful if it agrees to the last decimal, so that agreement is asserted rather than assumed.
 *
 * Background on what the map is for: `docs/open-graphics-decisions.md` item (w). Baked aperture
 * visibility explains 80 % of a deep room's spatial lighting error, applied at γ ≈ 0.7.
 */

/** Matches `make_box_uvs`'s default. Insets each slot so bilinear filtering cannot bleed one
 *  face's values into its neighbour's — at 64 px a slot edge is a whole texel of error. */
export const LIGHTMAP_UV_MARGIN = 0.04

/** Atlas grid: one column per axis, one row per normal sign. */
const ATLAS_COLS = 3
const ATLAS_ROWS = 2

export interface BoxAtlasUvInput {
  /** Flat `xyz` triples in the mesh's own local space, as `BufferGeometry.position`. */
  positions: ArrayLike<number>
  /** Triangle vertex indices. Pass `null` for a non-indexed geometry. */
  indices?: ArrayLike<number> | null
  margin?: number
}

export interface BoxAtlasUvResult {
  /** Flat `uv` pairs, one per vertex — ready for `setAttribute('uv1', …)`. */
  uv: Float32Array
  /**
   * Vertices that two faces in *different* atlas slots both wanted to place. Non-zero means
   * the geometry shares vertices across a hard normal boundary, so a per-vertex attribute
   * cannot represent the layout and the mesh needs its faces split first. Box and plane
   * geometries duplicate their corners per face, so this is 0 for the shell — but silence
   * here would otherwise be indistinguishable from a subtly wrong map.
   */
  conflicts: number
}

/** The two axes that are not `axis`, in ascending order — the in-slot coordinate pair. */
function otherAxes(axis: number): [number, number] {
  if (axis === 0) return [1, 2]
  if (axis === 1) return [0, 2]
  return [0, 1]
}

/**
 * Build the 3×2 box-atlas `uv1` for one mesh.
 *
 * Face normals are computed from the triangle's own winding rather than read from a normal
 * attribute: a shaded normal may be smoothed or flipped by the exporter, and the slot
 * assignment has to follow the geometry the bake actually saw.
 */
export function computeBoxAtlasUv({
  positions,
  indices = null,
  margin = LIGHTMAP_UV_MARGIN,
}: BoxAtlasUvInput): BoxAtlasUvResult {
  const vertexCount = Math.floor(positions.length / 3)
  const uv = new Float32Array(vertexCount * 2)
  const slotOf = new Int8Array(vertexCount).fill(-1)
  let conflicts = 0

  const min = [Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY, Number.POSITIVE_INFINITY]
  const max = [Number.NEGATIVE_INFINITY, Number.NEGATIVE_INFINITY, Number.NEGATIVE_INFINITY]
  for (let v = 0; v < vertexCount; v += 1) {
    for (let k = 0; k < 3; k += 1) {
      const value = positions[v * 3 + k]
      if (value < min[k]) min[k] = value
      if (value > max[k]) max[k] = value
    }
  }
  // A perfectly flat mesh has zero extent on one axis; clamp so it maps to 0 rather than NaN.
  const size = [0, 1, 2].map((k) => Math.max(max[k] - min[k], 1e-6))

  const triangleCount = indices ? Math.floor(indices.length / 3) : Math.floor(vertexCount / 3)
  for (let t = 0; t < triangleCount; t += 1) {
    const ia = indices ? indices[t * 3] : t * 3
    const ib = indices ? indices[t * 3 + 1] : t * 3 + 1
    const ic = indices ? indices[t * 3 + 2] : t * 3 + 2
    const ax = positions[ia * 3]
    const ay = positions[ia * 3 + 1]
    const az = positions[ia * 3 + 2]
    const e1 = [positions[ib * 3] - ax, positions[ib * 3 + 1] - ay, positions[ib * 3 + 2] - az]
    const e2 = [positions[ic * 3] - ax, positions[ic * 3 + 1] - ay, positions[ic * 3 + 2] - az]
    const n = [
      e1[1] * e2[2] - e1[2] * e2[1],
      e1[2] * e2[0] - e1[0] * e2[2],
      e1[0] * e2[1] - e1[1] * e2[0],
    ]

    // First maximum on a tie, matching Python's `max(range(3), key=…)`.
    let axis = 0
    for (let k = 1; k < 3; k += 1) {
      if (Math.abs(n[k]) > Math.abs(n[axis])) axis = k
    }
    const row = n[axis] >= 0 ? 0 : 1
    const col = axis
    const slot = row * ATLAS_COLS + col
    const [o1, o2] = otherAxes(axis)

    for (const vi of [ia, ib, ic]) {
      if (slotOf[vi] !== -1 && slotOf[vi] !== slot) conflicts += 1
      slotOf[vi] = slot
      const a = (positions[vi * 3 + o1] - min[o1]) / size[o1]
      const b = (positions[vi * 3 + o2] - min[o2]) / size[o2]
      uv[vi * 2] = (col + margin + a * (1 - 2 * margin)) / ATLAS_COLS
      uv[vi * 2 + 1] = (row + margin + b * (1 - 2 * margin)) / ATLAS_ROWS
    }
  }

  return { uv, conflicts }
}
