import { describe, expect, it } from 'vitest'
import { WALLS } from '../../apartment/constants'
import { buildDefaultPlan } from '../../floorplan/defaultPlan'
import { planLevels } from '../../floorplan/levels'
import { hdbMaisonette } from '../../floorplan/templates/hdb'
import type { FloorPlan } from '../../floorplan/types'
import type { FurnitureItem } from '../../furniture/types'
import { planAttenuationWalls } from './planAttenuationWalls'
import { computeWindowModifiers } from './windowLightModifiers'

/**
 * SUN-CURTAIN-PLAN (v0.31.5.101) — curtain/window sun attenuation must be
 * computed from the LOADED plan, not the default flat's constants.
 *
 * `CurtainLightController` passed `apartment/constants.ts`'s `WALLS` regardless
 * of which plan was loaded. That is worse than doing nothing: the curtain→window
 * match is positional (within 0.5 m of the wall, angularly aligned, spans
 * overlapping), and every plan sits near the origin, so a template curtain
 * silently attenuated whichever DEFAULT-FLAT window it happened to land near.
 * Measured before the fix: a blackout curtain drawn over the maisonette's
 * `em-kit-win` produced a scene factor of 0.878 — a plausible number generated by
 * a window that is not in the plan at all.
 */

/** A fully-drawn blackout curtain centred on a plan opening, 0.15 m off the wall. */
function curtainOn(plan: FloorPlan, openingId: string): FurnitureItem {
  const level = planLevels(plan).find((l) => l.openings.some((o) => o.id === openingId))!
  const op = level.openings.find((o) => o.id === openingId)!
  const w = level.walls.find((x) => x.id === op.wallId)!
  const dx = w.end[0] - w.start[0]
  const dz = w.end[1] - w.start[1]
  const len = Math.hypot(dx, dz)
  const ux = dx / len
  const uz = dz / len
  const t = op.offset + op.width / 2
  return {
    id: 'curtain-under-test',
    defId: 'curtains' as FurnitureItem['defId'],
    position: [w.start[0] + ux * t - uz * 0.15, w.start[1] + uz * t + ux * 0.15],
    // `wallAngle` is atan2(dz, dx); the matcher allows +-90 degrees off it.
    rotation: Math.atan2(dz, dx),
    props: { width: op.width, draw: 1, material: 'blackout' },
  } as FurnitureItem
}

const attenuation = (walls: Parameters<typeof computeWindowModifiers>[0], it: FurnitureItem) =>
  computeWindowModifiers(walls, [it], '').attenuation

describe('planAttenuationWalls', () => {
  it('CONTROL: the default flat is identical through the plan and through WALLS', () => {
    // The default plan is built from the same constants, so switching the source
    // must not move the number by even a float. Identity IS the claim here.
    const plan = buildDefaultPlan()
    const win = plan.openings.find((o) => o.kind === 'window')!
    const item = curtainOn(plan, win.id)
    const viaPlan = attenuation(planAttenuationWalls(plan, 'all'), item)
    const viaConstants = attenuation(WALLS, item)
    expect(viaPlan).toBe(viaConstants)
    // And the mechanism is actually firing — otherwise 1 === 1 would "pass".
    expect(viaPlan).toBeLessThan(1)
  })

  it("exposes the MAISONETTE's own windows, which the constants never contained", () => {
    const refIds = planAttenuationWalls(hdbMaisonette(), 'all').flatMap((w) =>
      w.cutouts.filter((c) => c.kind === 'window').map((c) => c.refId),
    )
    expect(refIds).toContain('em-kit-win')
    // The old source could not have: no `em-`/`emu-` id exists in the constants.
    const constIds = WALLS.flatMap((w) => w.cutouts.map((c) => c.refId))
    expect(constIds).not.toContain('em-kit-win')
  })

  it('a curtain drawn on a maisonette window now dims the sun through its OWN window', () => {
    const plan = hdbMaisonette()
    const item = curtainOn(plan, 'em-kit-win')
    expect(attenuation(planAttenuationWalls(plan, 'all'), item)).toBeLessThan(1)
  })

  it('scopes to the viewed storey', () => {
    // Curtains drawn upstairs should not be averaged against the open windows of
    // the floor below, so the upper level must expose only its own walls.
    const plan = hdbMaisonette()
    const upperIds = planAttenuationWalls(plan, 'em-up').map((w) => w.id)
    const groundIds = planAttenuationWalls(plan, 'all').map((w) => w.id)
    expect(upperIds.length).toBeGreaterThan(0)
    expect(upperIds.filter((id) => groundIds.includes(id))).toEqual([])
  })

  it('carries the opening geometry across, not just its id', () => {
    const plan = hdbMaisonette()
    const op = planLevels(plan)
      .flatMap((l) => l.openings)
      .find((o) => o.id === 'em-kit-win')!
    const cut = planAttenuationWalls(plan, 'all')
      .flatMap((w) => w.cutouts)
      .find((c) => c.refId === 'em-kit-win')!
    expect(cut.offset).toBe(op.offset)
    expect(cut.width).toBe(op.width)
    expect(cut.sill).toBe(op.sill)
    expect(cut.head).toBe(op.head)
  })
})
