import type { LayoutPreset } from './types'

export const brokenPlan: LayoutPreset = {
  id: 'broken-plan',
  group: 'layout',
  name: 'Broken-Plan Living',
  description:
    'Re-modelled L/D: a slat screen zones the lounge from the dining without closing it.',
  dryFloor: 'floor-wood-oak',
  wall: 'wall-paint-warm',
  style: {},
  livingDining: [
    // ── Lounge (north), facing the east media wall ──
    {
      id: 'bp-sofa',
      defId: 'sofa-3seat',
      position: [9.6, 2.55],
      rotation: Math.PI / 2,
      props: { color: '#7d8a82', material: 'fabric', pattern: 'plain', pillowColor: '#b5683f' },
    },
    {
      id: 'bp-console',
      defId: 'tv-console',
      position: [12.1, 2.45],
      rotation: -Math.PI / 2,
      props: { width: 1.6, base: 'legs', color: '#5a3f2a', finish: 'wood' },
    },
    {
      id: 'bp-tv',
      defId: 'tv-wall',
      position: [12.45, 2.45],
      rotation: -Math.PI / 2,
      props: {
        size: '55',
        mount: 'wall',
        mountHeight: 1.3,
        screen: 'on',
        screenContent: 'landscape',
      },
    },
    {
      id: 'bp-soundbar',
      defId: 'soundbar',
      position: [12.42, 2.45],
      rotation: -Math.PI / 2,
      props: { width: 1.2, mountHeight: 0.78, grille: 'fabric', color: '#1c1c1e' },
    },
    {
      id: 'bp-cove',
      defId: 'cove-light',
      position: [12.5, 2.6],
      rotation: -Math.PI / 2,
      props: { length: 3.4, mountHeight: 2.38 },
    },
    {
      id: 'bp-rug',
      defId: 'rug',
      position: [10.95, 2.55],
      rotation: 0,
      props: {
        width: 2.0,
        depth: 1.8,
        color: '#d8cdb8',
        borderColor: '#9a8a6a',
        pattern: 'plain',
      },
    },
    {
      id: 'bp-coffee',
      defId: 'coffee-table',
      position: [10.95, 2.55],
      rotation: Math.PI / 2,
      props: { shape: 'oval', width: 1.0, depth: 0.55, color: '#5a3f2a', finish: 'wood' },
    },
    {
      id: 'bp-ottoman',
      defId: 'ottoman',
      position: [11.0, 3.4],
      rotation: 0,
      props: {
        shape: 'round',
        width: 0.5,
        depth: 0.5,
        color: '#b5683f',
        material: 'fabric',
        tufting: 'buttons',
      },
    },
    { id: 'bp-fan', defId: 'ceiling-fan', position: [10.95, 2.55], rotation: 0, props: {} },
    { id: 'bp-aircon', defId: 'aircon-unit', position: [10.6, 1.55], rotation: 0, props: {} },
    {
      id: 'bp-curtain',
      defId: 'curtains',
      position: [10.85, 1.5],
      rotation: 0,
      props: { width: 2.8, height: 2.3, color: '#e6ddca' },
    },
    // ── The zoning screen between lounge and dining (partial width → walkway east) ──
    {
      id: 'bp-divider',
      defId: 'room-divider',
      position: [9.95, 3.95],
      rotation: 0,
      props: { width: 1.5, height: 1.8, style: 'slat', color: '#5a3f2a', finish: 'wood' },
    },
    // ── Dining (south) ──
    {
      id: 'bp-dining',
      defId: 'dining-table-4',
      position: [10.7, 5.75],
      rotation: 0,
      props: { seats: '6', shape: 'oval', topColor: '#5a3f2a', legColor: '#3a2c1d' },
    },
    {
      id: 'bp-dc-n1',
      defId: 'dining-chair',
      position: [9.95, 5.05],
      rotation: 0,
      props: { style: 'wood', seatColor: '#9a6b3f' },
    },
    {
      id: 'bp-dc-n2',
      defId: 'dining-chair',
      position: [10.7, 5.05],
      rotation: 0,
      props: { style: 'wood', seatColor: '#9a6b3f' },
    },
    {
      id: 'bp-dc-n3',
      defId: 'dining-chair',
      position: [11.45, 5.05],
      rotation: 0,
      props: { style: 'wood', seatColor: '#9a6b3f' },
    },
    {
      id: 'bp-dc-s1',
      defId: 'dining-chair',
      position: [9.95, 6.45],
      rotation: Math.PI,
      props: { style: 'wood', seatColor: '#9a6b3f' },
    },
    {
      id: 'bp-dc-s2',
      defId: 'dining-chair',
      position: [10.7, 6.45],
      rotation: Math.PI,
      props: { style: 'wood', seatColor: '#9a6b3f' },
    },
    {
      id: 'bp-dc-s3',
      defId: 'dining-chair',
      position: [11.45, 6.45],
      rotation: Math.PI,
      props: { style: 'wood', seatColor: '#9a6b3f' },
    },
    {
      id: 'bp-pendant',
      defId: 'ceiling-light',
      position: [10.7, 5.75],
      rotation: 0,
      props: { style: 'pendant', shade: 'drum' },
    },
    {
      id: 'bp-shoe',
      defId: 'shoe-cabinet',
      position: [12.35, 7.45],
      rotation: -Math.PI / 2,
      props: { width: 0.9, depth: 0.3 },
    },
  ],
}
