import type { LayoutPreset } from './types'

export const entertainer: LayoutPreset = {
  id: 'entertainer',
  name: "Entertainer's Lounge",
  description: 'Re-modelled L/D: L-sofa to a media credenza + bar cart, six-seat dining.',
  dryFloor: 'floor-wood-walnut',
  wall: 'wall-paint-greige',
  style: {},
  livingDining: [
    // ── Lounge zone (north): sectional faces the east media wall ──
    {
      id: 'es-sectional',
      defId: 'sofa-lshape',
      // L-sofa true footprint is 1.95 m deep; its back run must clear the west
      // partition at x≈9.1, so it sits a touch off the wall (see openLounge).
      position: [10.2, 2.75],
      rotation: -Math.PI / 2,
      props: {
        width: 2.6,
        depth: 0.95,
        chaise: 1.0,
        chaiseSide: 'right',
        color: '#4a5a63',
        material: 'fabric',
        pattern: 'plain',
        pillowColor: '#c9a24b',
      },
    },
    {
      id: 'es-rug',
      defId: 'rug',
      position: [11.0, 2.75],
      rotation: 0,
      props: {
        width: 2.2,
        depth: 2.6,
        color: '#cfc6b4',
        borderColor: '#3a352c',
        pattern: 'plain',
      },
    },
    {
      id: 'es-coffee',
      defId: 'coffee-table',
      position: [11.05, 2.75],
      rotation: 0,
      props: { shape: 'oval', width: 1.1, depth: 0.6, color: '#3f2f22', finish: 'wood' },
    },
    {
      id: 'es-feature',
      defId: 'feature-wall',
      position: [12.53, 2.75],
      rotation: -Math.PI / 2,
      props: { width: 2.8, height: 2.55, style: 'slat', color: '#4a3a2c', finish: 'wood' },
    },
    // Media credenza — a long sideboard under the wall-mounted TV.
    {
      id: 'es-credenza',
      defId: 'sideboard',
      position: [12.32, 2.75],
      rotation: -Math.PI / 2,
      props: {
        width: 2.0,
        depth: 0.42,
        bays: 4,
        front: 'mixed',
        legs: 'tapered',
        handle: 'bar',
        color: '#4a3a2c',
        finish: 'wood',
      },
    },
    {
      id: 'es-tv',
      defId: 'tv-wall',
      position: [12.45, 2.75],
      rotation: -Math.PI / 2,
      props: {
        size: '65',
        mount: 'wall',
        mountHeight: 1.35,
        screen: 'on',
        screenContent: 'sunset',
      },
    },
    {
      id: 'es-cove',
      defId: 'cove-light',
      position: [12.5, 2.6],
      rotation: -Math.PI / 2,
      props: { length: 3.4, mountHeight: 2.38 },
    },
    // Bar cart tucked against the east wall between lounge and dining.
    {
      id: 'es-barcart',
      defId: 'bar-cart',
      position: [12.05, 4.55],
      rotation: 0,
      props: { tiers: 3, frame: 'brass', shelf: 'glass' },
    },
    {
      id: 'es-plant',
      defId: 'potted-plant',
      position: [9.0, 4.5],
      rotation: 0,
      props: { type: 'fiddle', size: 'large', potShape: 'cylinder', leafColor: '#3f7a3f' },
    },
    {
      id: 'es-lamp',
      defId: 'floor-lamp',
      position: [11.5, 1.85],
      rotation: 0,
      props: { base: 'tripod', shade: 'drum' },
    },
    { id: 'es-fan', defId: 'ceiling-fan', position: [10.7, 2.75], rotation: 0, props: {} },
    { id: 'es-aircon', defId: 'aircon-unit', position: [10.6, 1.55], rotation: 0, props: {} },
    {
      id: 'es-curtain',
      defId: 'curtains',
      position: [10.85, 1.5],
      rotation: 0,
      props: { width: 2.8, height: 2.3, color: '#cfc6b4' },
    },
    // ── Dining zone (south), open to the lounge ──
    {
      id: 'es-dining',
      defId: 'dining-table-4',
      position: [10.7, 5.75],
      rotation: 0,
      props: { seats: '6', shape: 'oval', topColor: '#3f2f22', legColor: '#2c2118' },
    },
    {
      id: 'es-dc-n1',
      defId: 'dining-chair',
      position: [9.95, 5.05],
      rotation: 0,
      props: { style: 'upholstered', seatColor: '#4a5a63' },
    },
    {
      id: 'es-dc-n2',
      defId: 'dining-chair',
      position: [10.7, 5.05],
      rotation: 0,
      props: { style: 'upholstered', seatColor: '#4a5a63' },
    },
    {
      id: 'es-dc-n3',
      defId: 'dining-chair',
      position: [11.45, 5.05],
      rotation: 0,
      props: { style: 'upholstered', seatColor: '#4a5a63' },
    },
    {
      id: 'es-dc-s1',
      defId: 'dining-chair',
      position: [9.95, 6.45],
      rotation: Math.PI,
      props: { style: 'upholstered', seatColor: '#4a5a63' },
    },
    {
      id: 'es-dc-s2',
      defId: 'dining-chair',
      position: [10.7, 6.45],
      rotation: Math.PI,
      props: { style: 'upholstered', seatColor: '#4a5a63' },
    },
    {
      id: 'es-dc-s3',
      defId: 'dining-chair',
      position: [11.45, 6.45],
      rotation: Math.PI,
      props: { style: 'upholstered', seatColor: '#4a5a63' },
    },
    {
      id: 'es-pendant',
      defId: 'ceiling-light',
      position: [10.7, 5.75],
      rotation: 0,
      props: { style: 'pendant', shade: 'drum' },
    },
    {
      id: 'es-shoe',
      defId: 'shoe-cabinet',
      position: [12.35, 7.45],
      rotation: -Math.PI / 2,
      props: { width: 0.9, depth: 0.3 },
    },
  ],
}
