import type { LayoutPreset } from './types'

export const minimalist: LayoutPreset = {
  id: 'minimalist',
  name: 'Minimalist',
  description: 'Re-modelled L/D: pared-back, low furniture, lots of open floor.',
  dryFloor: 'floor-wood-ash',
  wall: 'wall-paint-soft-white',
  style: {},
  // Subset of the proven default positions (omits clutter) → always valid.
  livingDining: [
    {
      id: 'mn-sofa',
      defId: 'sofa-3seat',
      position: [9.6, 2.55],
      rotation: Math.PI / 2,
      props: { armStyle: 'low', color: '#dad7cf', material: 'fabric', accentPillows: 'none' },
    },
    {
      id: 'mn-console',
      defId: 'tv-console',
      position: [12.1, 2.45],
      rotation: -Math.PI / 2,
      props: { width: 1.6, base: 'plinth', color: '#cdb696', finish: 'wood' },
    },
    {
      id: 'mn-tv',
      defId: 'tv-wall',
      position: [12.45, 2.45],
      rotation: -Math.PI / 2,
      props: { size: '55', mount: 'wall', mountHeight: 1.3, screen: 'off' },
    },
    {
      id: 'mn-cove',
      defId: 'cove-light',
      position: [12.5, 2.6],
      rotation: -Math.PI / 2,
      props: { length: 3.4, mountHeight: 2.38 },
    },
    {
      id: 'mn-rug',
      defId: 'rug',
      position: [10.95, 2.55],
      rotation: 0,
      props: {
        width: 2.0,
        depth: 1.8,
        color: '#e6e0d2',
        borderColor: '#d8cdb8',
        pattern: 'plain',
      },
    },
    {
      id: 'mn-coffee',
      defId: 'coffee-table',
      position: [10.95, 2.55],
      rotation: Math.PI / 2,
      props: { shape: 'oval', width: 1.0, depth: 0.55, color: '#cdb696', finish: 'wood' },
    },
    { id: 'mn-fan', defId: 'ceiling-fan', position: [10.95, 2.55], rotation: 0, props: {} },
    { id: 'mn-aircon', defId: 'aircon-unit', position: [10.6, 1.55], rotation: 0, props: {} },
    {
      id: 'mn-curtain',
      defId: 'curtains',
      position: [10.85, 1.5],
      rotation: 0,
      props: { width: 2.8, height: 2.3, color: '#e6e0d2' },
    },
    {
      id: 'mn-dining',
      defId: 'dining-table-4',
      position: [10.55, 5.2],
      rotation: 0,
      props: { seats: '4', shape: 'round', topColor: '#cdb696', legColor: '#b39a72' },
    },
    {
      id: 'mn-dc-1',
      defId: 'dining-chair',
      position: [10.2, 4.45],
      rotation: 0,
      props: { style: 'wood', seatColor: '#cdb696' },
    },
    {
      id: 'mn-dc-2',
      defId: 'dining-chair',
      position: [10.9, 4.45],
      rotation: 0,
      props: { style: 'wood', seatColor: '#cdb696' },
    },
    {
      id: 'mn-dc-3',
      defId: 'dining-chair',
      position: [10.2, 5.95],
      rotation: Math.PI,
      props: { style: 'wood', seatColor: '#cdb696' },
    },
    {
      id: 'mn-dc-4',
      defId: 'dining-chair',
      position: [10.9, 5.95],
      rotation: Math.PI,
      props: { style: 'wood', seatColor: '#cdb696' },
    },
    {
      id: 'mn-pendant',
      defId: 'ceiling-light',
      position: [10.55, 5.2],
      rotation: 0,
      props: { style: 'pendant', shade: 'globe' },
    },
    {
      id: 'mn-plant',
      defId: 'potted-plant',
      position: [12.2, 6.3],
      rotation: 0,
      props: { type: 'snake', size: 'large', potShape: 'cylinder' },
    },
    {
      id: 'mn-shoe',
      defId: 'shoe-cabinet',
      position: [12.35, 7.45],
      rotation: -Math.PI / 2,
      props: { width: 0.9, depth: 0.3 },
    },
  ],
}
