import type { LayoutPreset } from './types'

export const openLounge: LayoutPreset = {
  id: 'open-lounge',
  name: 'Open-Concept Lounge',
  description: 'Re-modelled L/D: L-sectional facing a media wall, open dining.',
  dryFloor: 'floor-wood-oak',
  wall: 'wall-paint-greige',
  style: {},
  livingDining: [
    // ── Lounge zone (north), seating faces the east media wall ──
    {
      id: 'ol-sectional',
      defId: 'sofa-lshape',
      // The L-sofa's true footprint is 1.95 m deep (main run + chaise); its back
      // run must clear the west partition at x≈9.1, so it sits a touch off the wall.
      position: [10.2, 2.75],
      rotation: -Math.PI / 2,
      props: {
        width: 2.6,
        depth: 0.95,
        chaise: 1.0,
        chaiseSide: 'right',
        color: '#6f7a74',
        material: 'fabric',
        pattern: 'herringbone',
        pillowColor: '#c4683f',
      },
    },
    {
      id: 'ol-rug',
      defId: 'rug',
      position: [11.0, 2.75],
      rotation: 0,
      props: {
        width: 2.2,
        depth: 2.6,
        color: '#cfc6b4',
        borderColor: '#5a4a32',
        pattern: 'plain',
      },
    },
    {
      id: 'ol-coffee',
      defId: 'coffee-table',
      position: [11.05, 2.75],
      rotation: 0,
      props: { shape: 'oval', width: 1.1, depth: 0.6, color: '#5a3f2a', finish: 'wood' },
    },
    {
      id: 'ol-feature',
      defId: 'feature-wall',
      position: [12.53, 2.75],
      rotation: -Math.PI / 2,
      props: { width: 2.8, height: 2.55, style: 'fluted', color: '#6f553f', finish: 'wood' },
    },
    {
      id: 'ol-media',
      defId: 'tv-console',
      position: [12.2, 2.75],
      rotation: -Math.PI / 2,
      props: { width: 2.0, base: 'legs', front: 'doors', color: '#4a3a2c', finish: 'wood' },
    },
    {
      id: 'ol-tv',
      defId: 'tv-wall',
      position: [12.42, 2.75],
      rotation: -Math.PI / 2,
      props: {
        size: '65',
        mount: 'wall',
        mountHeight: 1.3,
        screen: 'on',
        screenContent: 'landscape',
      },
    },
    {
      id: 'ol-cove',
      defId: 'cove-light',
      position: [12.5, 2.6],
      rotation: -Math.PI / 2,
      props: { length: 3.4, mountHeight: 2.38 },
    },
    {
      id: 'ol-plant',
      defId: 'potted-plant',
      position: [9.0, 4.5],
      rotation: 0,
      props: { type: 'fiddle', size: 'large', potShape: 'square', leafColor: '#3f7a3f' },
    },
    {
      id: 'ol-lamp',
      defId: 'floor-lamp',
      position: [11.5, 1.85],
      rotation: 0,
      props: { base: 'tripod', shade: 'drum' },
    },
    { id: 'ol-fan', defId: 'ceiling-fan', position: [10.7, 2.75], rotation: 0, props: {} },
    { id: 'ol-aircon', defId: 'aircon-unit', position: [10.6, 1.55], rotation: 0, props: {} },
    {
      id: 'ol-curtain',
      defId: 'curtains',
      position: [10.85, 1.5],
      rotation: 0,
      props: { width: 2.8, height: 2.3, color: '#cfc6b4' },
    },
    // ── Dining zone (south), open to the lounge ──
    {
      id: 'ol-dining',
      defId: 'dining-table-4',
      position: [10.7, 5.75],
      rotation: 0,
      props: { seats: '6', shape: 'oval', topColor: '#5a3f2a', legColor: '#3a2c1d' },
    },
    {
      id: 'ol-dc-n1',
      defId: 'dining-chair',
      position: [9.95, 5.05],
      rotation: 0,
      props: { style: 'upholstered', seatColor: '#8a7f70' },
    },
    {
      id: 'ol-dc-n2',
      defId: 'dining-chair',
      position: [10.7, 5.05],
      rotation: 0,
      props: { style: 'upholstered', seatColor: '#8a7f70' },
    },
    {
      id: 'ol-dc-n3',
      defId: 'dining-chair',
      position: [11.45, 5.05],
      rotation: 0,
      props: { style: 'upholstered', seatColor: '#8a7f70' },
    },
    {
      id: 'ol-dc-s1',
      defId: 'dining-chair',
      position: [9.95, 6.45],
      rotation: Math.PI,
      props: { style: 'upholstered', seatColor: '#8a7f70' },
    },
    {
      id: 'ol-dc-s2',
      defId: 'dining-chair',
      position: [10.7, 6.45],
      rotation: Math.PI,
      props: { style: 'upholstered', seatColor: '#8a7f70' },
    },
    {
      id: 'ol-dc-s3',
      defId: 'dining-chair',
      position: [11.45, 6.45],
      rotation: Math.PI,
      props: { style: 'upholstered', seatColor: '#8a7f70' },
    },
    {
      id: 'ol-pendant',
      defId: 'ceiling-light',
      position: [10.7, 5.75],
      rotation: 0,
      props: { style: 'pendant', shade: 'drum' },
    },
    // ── Entry alcove (SE): shoe storage only — kept clear for the door. ──
    {
      id: 'ol-shoe',
      defId: 'shoe-cabinet',
      position: [12.35, 7.45],
      rotation: -Math.PI / 2,
      props: { width: 0.9, depth: 0.3 },
    },
  ],
  extraItems: [
    {
      id: 'ol-bench',
      defId: 'bench',
      position: [1.05, 2.55],
      rotation: 0,
      props: { style: 'storage', material: 'fabric', color: '#8a6b48', legColor: '#4a3722' },
    },
  ],
}
