import type { LayoutPreset } from './types'

export const wfhStudio: LayoutPreset = {
  id: 'wfh-studio',
  name: 'Work-From-Home',
  description: 'Re-modelled L/D: compact lounge, a study nook + shelving, round dining.',
  dryFloor: 'floor-wood-ash',
  wall: 'wall-paint-soft-white',
  style: {},
  livingDining: [
    // ── Compact lounge (north) facing the east media wall ──
    {
      id: 'wfh-sofa',
      defId: 'sofa-2seat',
      position: [9.65, 2.35],
      rotation: Math.PI / 2,
      props: {
        width: 1.6,
        depth: 0.9,
        color: '#8a9aa0',
        material: 'fabric',
        pattern: 'plain',
        pillowColor: '#3b5a7d',
      },
    },
    {
      id: 'wfh-rug',
      defId: 'rug',
      position: [11.0, 2.5],
      rotation: 0,
      props: {
        width: 1.7,
        depth: 1.7,
        color: '#dfd8c8',
        borderColor: '#5a4a32',
        pattern: 'striped',
      },
    },
    {
      id: 'wfh-coffee',
      defId: 'coffee-table',
      position: [11.0, 2.5],
      rotation: 0,
      props: { shape: 'round', width: 0.9, depth: 0.9, color: '#9a6b3f', finish: 'wood' },
    },
    {
      id: 'wfh-media',
      defId: 'tv-console',
      position: [12.2, 2.5],
      rotation: -Math.PI / 2,
      props: { width: 1.6, base: 'legs', color: '#9a6b3f', finish: 'wood' },
    },
    {
      id: 'wfh-tv',
      defId: 'tv-wall',
      position: [12.48, 2.5],
      rotation: -Math.PI / 2,
      props: {
        size: '55',
        mount: 'wall',
        mountHeight: 1.3,
        screen: 'on',
        screenContent: 'abstract',
      },
    },
    {
      id: 'wfh-cove',
      defId: 'cove-light',
      position: [12.5, 2.6],
      rotation: -Math.PI / 2,
      props: { length: 3.4, mountHeight: 2.38 },
    },
    { id: 'wfh-fan', defId: 'ceiling-fan', position: [10.6, 2.8], rotation: 0, props: {} },
    { id: 'wfh-aircon', defId: 'aircon-unit', position: [10.6, 1.55], rotation: 0, props: {} },
    {
      id: 'wfh-curtain',
      defId: 'curtains',
      position: [10.85, 1.5],
      rotation: 0,
      props: { width: 2.8, height: 2.3, color: '#e6e0d2' },
    },
    // ── Study nook against the west wall ──
    {
      id: 'wfh-desk',
      defId: 'desk',
      position: [9.5, 4.5],
      rotation: Math.PI / 2,
      props: { width: 1.4, depth: 0.6, legStyle: 'hairpin', color: '#caa46a', finish: 'wood' },
    },
    {
      id: 'wfh-chair',
      defId: 'office-chair',
      position: [10.3, 4.5],
      rotation: -Math.PI / 2,
      props: { style: 'mesh', color: '#3a3f45' },
    },
    {
      id: 'wfh-monitor',
      defId: 'monitor',
      position: [9.35, 4.5],
      rotation: Math.PI / 2,
      props: { screen: 'on', screenContent: 'abstract' },
    },
    {
      id: 'wfh-shelf',
      defId: 'bookshelf',
      position: [9.35, 5.7],
      rotation: Math.PI / 2,
      props: { width: 0.9, height: 1.8, shelfCount: 5, color: '#caa46a', finish: 'wood' },
    },
    {
      id: 'wfh-plant',
      defId: 'potted-plant',
      position: [12.1, 5.2],
      rotation: 0,
      props: { type: 'palm', size: 'large', leafColor: '#4a7a44' },
    },
    // ── Round dining (south alcove) ──
    {
      id: 'wfh-dining',
      defId: 'dining-table-4',
      position: [10.95, 6.0],
      rotation: 0,
      props: { seats: '4', shape: 'round', topColor: '#9a6b3f', legColor: '#6b4f34' },
    },
    {
      id: 'wfh-dc-1',
      defId: 'dining-chair',
      position: [10.95, 5.25],
      rotation: 0,
      props: { style: 'wood', seatColor: '#9a6b3f' },
    },
    {
      id: 'wfh-dc-2',
      defId: 'dining-chair',
      position: [10.95, 6.75],
      rotation: Math.PI,
      props: { style: 'wood', seatColor: '#9a6b3f' },
    },
    {
      id: 'wfh-dc-3',
      defId: 'dining-chair',
      position: [12.0, 6.0],
      rotation: -Math.PI / 2,
      props: { style: 'wood', seatColor: '#9a6b3f' },
    },
    {
      id: 'wfh-pendant',
      defId: 'ceiling-light',
      position: [10.95, 6.0],
      rotation: 0,
      props: { style: 'pendant', shade: 'globe' },
    },
    {
      id: 'wfh-shoe',
      defId: 'shoe-cabinet',
      position: [12.35, 7.45],
      rotation: -Math.PI / 2,
      props: { width: 0.9, depth: 0.3, style: 'open' },
    },
  ],
}
