/**
 * Feature-flag type vocabulary — the `FeatureFlag` union (every gateable feature),
 * the per-flag `FlagDef` shape, and the `FlagOverrides` map. Kept separate from the
 * registry data (`./registry`) and the resolution logic (`./resolve`) so each stays
 * small and focused; all three are re-exported from `../featureFlags`.
 */

export type FeatureFlag =
  | 'report'
  | 'walkthrough'
  | 'sunStudy'
  | 'measure'
  | 'budget'
  | 'clearanceChecks'
  | 'versions'
  | 'history'
  | 'shareExport'
  | 'floorPlanEditor'
  | 'smartStart'
  | 'layoutReroll'
  | 'textBrief'
  | 'panorama'
  | 'panoTour'
  | 'renderPresets'
  | 'lightMoodPresets'
  | 'hqRender'
  | 'hqAiDenoise'
  | 'vrWalkthrough'
  | 'savedViews'
  | 'backdrops'
  | 'packs'
  | 'remoteMaterials'
  | 'remoteFurniture'
  | 'modelUpload'
  | 'aiPhotoreal'
  | 'aiWalls'
  | 'aiPlanGenerate'
  | 'ikeaLive'
  | 'localAssets'
  | 'livePrices'
  | 'drawings'
  | 'daylight'
  | 'designScore'
  | 'accessibility'
  | 'moodboard'
  | 'shareCard'
  | 'paletteFromPhoto'
  | 'dxfExport'
  | 'boq'
  | 'sceneExport3d'
  | 'batchRender'
  | 'shopExport'
  | 'suggestions'
  | 'electricalPlan'
  | 'mountHeights'
  | 'copyAppearance'
  | 'userSets'
  | 'furnitureGroups'
  | 'designerPicks'
  | 'materialComposer'
  | 'finishRecolor'
  | 'ceilingDesign'
  | 'presentation'
  | 'pbrSurfaces'
  | 'comments'
  | 'finishDnd'
  | 'finishEyedropper'
  | 'parametricFurniture'
  | 'kitchenCabinets'
  | 'productConfigurator'
  | 'renderCompare'
  | 'stagingReveal'
  | 'timeCompare'
  | 'versionCompareView'
  | 'dayNightClip'
  | 'styleTransfer'
  | 'styleQuiz'
  | 'shortcutsHelp'
  | 'itemDimensionReadout'
  | 'wallAccentPicker'
  | 'bulkAppearance'
  | 'assetCredits'
  | 'crownMolding'
  | 'windowGlassTint'
  | 'curtainLightEffect'
  | 'walkCameraControls'
  | 'replaceSimilar'
  | 'customBackdrop'
  | 'paintVisualizer'
  | 'planLabels'
  | 'plumbingPlan'
  | 'itemAsLight'
  | 'aiLayout'
  | 'planPolyline'
  | 'planTraceBackdrop'
  | 'tiltFurniture'
  | 'catalogModelInfo'
  | 'curvedWalls'
  | 'slopingWalls'
  | 'wallBaseboard'
  | 'planGuides'
  | 'cornerFillet'
  | 'dimensionChain'
  | 'gapSuggest'
  | 'triplanarWalls'
  | 'hdriEnvironment'
  | 'wallThickness'
  | 'wallStructure'
  | 'unroomedFlag'
  | 'planIntegrity'
  | 'planScale'
  | 'viewInAr'
  | 'floorTexture'
  | 'planCompass'
  | 'contactShadows'
  | 'cornerAo'
  | 'drawingCallouts'
  | 'quoteTemplate'
  | 'priceRules'
  | 'catalogFavourites'
  | 'catalogFits'
  | 'catalogFitsFilter'
  | 'catalogRoomAware'
  | 'catalogRecents'
  | 'catalogCompare'
  | 'roomStarters'
  | 'wallNumericEntry'
  | 'radialArray'
  | 'pathArray'
  | 'iesLights'
  | 'cameraDof'
  | 'proceduralSky'
  | 'importSh3d'
  | 'importSh3f'
  | 'smartRotateSnap'
  | 'stampPlace'
  | 'scatterFill'
  | 'planMirrorRegion'
  | 'planGridSnap'
  | 'roomInset'
  | 'roomReorder'
  | 'tileBreakup'
  | 'pomFloors'
  | 'elementColors'
  | 'openingStyles'
  | 'itemOpacity'
  | 'ceilingFinish'
  | 'saveMaterials'
  | 'masterPalette'
  | 'palettePresets'
  | 'layerOrder'
  | 'contextMenu'
  | 'infoCallouts'
  | 'newBadges'
  | 'densityMode'
  | 'proUpsell'
  | 'ambientFx'
  | 'furnitureMotion'
  | 'accounts'
  | 'sharedLibrary'
  | 'walkWindowFixtures'
  | 'walkScreens'
  | 'walkLights'
  | 'cabinetOpen'
  | 'minimapTeleport'
  | 'planFurnish'
  | 'frameSelection'
  | 'altDragDuplicate'
  | 'isolateSelection'
  | 'mirrorSelection'
  | 'twoPointPerspective'
  | 'parallelProjection'
  | 'catalogResize'
  | 'catalogFilters'
  | 'glbDesigner'
  | 'assetConfigurableExport'
  | 'assetSets'
  | 'petFittings'
  | 'petProfile'
  | 'petCompliance'
  | 'suggestedViews'
  | 'profiler'
  | 'walkMeasure'
  | 'aiDesignChat'
  | 'shareCardNative'
  | 'itemMeta'
  | 'mepEditor'
  | 'switchCircuits'
  | 'settingOutDims'
  | 'carpentrySheets'
  | 'rcpSheet'
  | 'parametricStairs'
  | 'parametricRoof'
  | 'airconSizing'
  | 'airconSystem'
  | 'ceilingClearance'
  | 'hackabilityOverlay'
  | 'ocsStarter'
  | 'floorLoading'
  | 'renoRulesPack'
  | 'renoBudget'

export interface FlagDef {
  /** Short human label for the dev flags panel. */
  label: string
  /** What the flag gates. */
  description: string
  /** Production default when no override applies. */
  default: boolean
  /** Forced off in a production build (a dev/QA-only surface). */
  devOnly?: boolean
  /**
   * UI tier: `simple` features are part of the minimal core experience and show
   * in both Simple and Pro mode; `pro` features are advanced/professional and are
   * **forced off in Simple mode** (the app's default), keeping the simple UI
   * uncluttered. Every flag must declare a tier (see CLAUDE.md).
   */
  tier: 'simple' | 'pro'
}

export type FlagOverrides = Partial<Record<FeatureFlag, boolean>>
