import type { FurnitureDef } from '../types'

/** appliances furniture definitions. Part of the built-in catalog (see ../builtinCatalog.ts). */
export const APPLIANCES_DEFS = {
  // ── Appliances ──────────────────────────────────────────────────────────
  microwave: {
    kind: 'parametric',
    id: 'microwave',
    name: 'Microwave',
    keywords: ['microwave oven'],
    category: 'appliances',
    primitive: 'Microwave',
    defaultFootprint: { w: 0.5, d: 0.36, h: 0.3 },
    verticalSpan: { base: 0.9, top: 1.22 },
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.2,
        step: 0.02,
        default: 0.9,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#3b3e44' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'gloss',
        options: [
          { value: 'matte', label: 'Matte' },
          { value: 'steel', label: 'Stainless steel' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
    ],
  },
  refrigerator: {
    kind: 'parametric',
    id: 'refrigerator',
    name: 'Refrigerator',
    category: 'appliances',
    keywords: ['fridge', 'freezer'],
    primitive: 'Refrigerator',
    defaultFootprint: { w: 0.7, d: 0.7, h: 1.78 },
    paramSchema: [
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 1.4,
        max: 1.9,
        step: 0.02,
        default: 1.78,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#d8dade' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'steel',
        options: [
          { value: 'matte', label: 'Matte' },
          { value: 'steel', label: 'Stainless steel' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
    ],
  },
  'tv-wall': {
    kind: 'parametric',
    id: 'tv-wall',
    name: 'TV (wall-mounted)',
    keywords: ['television', 'telly', 'flat screen'],
    category: 'appliances',
    primitive: 'FlatscreenTV',
    defaultFootprint: { w: 1.25, d: 0.1, h: 0.75 },
    mounted: true,
    verticalSpan: { base: 0.9, top: 1.85 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'size',
        label: 'Size',
        default: '55',
        options: [
          { value: '43', label: '43"' },
          { value: '55', label: '55"' },
          { value: '65', label: '65"' },
          { value: '75', label: '75"' },
        ],
      },
      {
        kind: 'enum',
        key: 'mount',
        label: 'Mount',
        default: 'wall',
        options: [
          { value: 'wall', label: 'Wall' },
          { value: 'stand', label: 'On stand' },
        ],
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Centre height',
        min: 1.0,
        max: 1.7,
        step: 0.05,
        default: 1.35,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'screen',
        label: 'Screen',
        default: 'off',
        options: [
          { value: 'off', label: 'Off' },
          { value: 'on', label: 'On' },
        ],
      },
      {
        kind: 'enum',
        key: 'screenContent',
        label: 'On-screen',
        default: 'landscape',
        options: [
          { value: 'landscape', label: 'Landscape' },
          { value: 'sunset', label: 'Sunset' },
          { value: 'abstract', label: 'Abstract' },
        ],
      },
    ],
  },
  'aircon-unit': {
    kind: 'parametric',
    id: 'aircon-unit',
    name: 'Aircon (wall unit)',
    keywords: ['air conditioner', 'air-con', 'ac unit', 'hvac', 'split unit'],
    category: 'appliances',
    primitive: 'AirconUnit',
    defaultFootprint: { w: 0.84, d: 0.22, h: 0.3 },
    mounted: true,
    verticalSpan: { base: 1.9, top: 2.55 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.7,
        max: 1.1,
        step: 0.02,
        default: 0.84,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 1.9,
        max: 2.5,
        step: 0.05,
        default: 2.25,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Finish', default: '#f3f3f0' },
    ],
  },
  'standing-fan': {
    kind: 'parametric',
    id: 'standing-fan',
    name: 'Standing fan',
    keywords: ['pedestal fan', 'floor fan'],
    category: 'appliances',
    primitive: 'StandingFan',
    defaultFootprint: { w: 0.54, d: 0.54, h: 1.32 },
    paramSchema: [
      {
        kind: 'number',
        key: 'height',
        label: 'Head height',
        min: 0.9,
        max: 1.3,
        step: 0.05,
        default: 1.1,
        unit: 'm',
      },
      { kind: 'color', key: 'bodyColor', label: 'Body', default: '#e8e6e1' },
      { kind: 'color', key: 'bladeColor', label: 'Blades', default: '#dcddd8' },
    ],
  },
  'wine-cooler': {
    kind: 'parametric',
    id: 'wine-cooler',
    name: 'Wine cooler',
    category: 'appliances',
    keywords: ['wine fridge', 'beverage cooler', 'drinks fridge', 'cellar', 'kitchen'],
    primitive: 'WineCooler',
    defaultFootprint: { w: 0.45, d: 0.6, h: 0.85 },
    frontClearance: 0.5,
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.3,
        max: 0.6,
        step: 0.05,
        default: 0.45,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#2c2f33' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'steel',
        options: [
          { value: 'steel', label: 'Stainless steel' },
          { value: 'matte', label: 'Matte black' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
    ],
  },
  'built-in-oven': {
    kind: 'parametric',
    id: 'built-in-oven',
    name: 'Built-in oven',
    category: 'appliances',
    keywords: ['oven', 'wall oven', 'built-under', 'kitchen', 'baking'],
    primitive: 'Oven',
    defaultFootprint: { w: 0.6, d: 0.6, h: 0.6 },
    frontClearance: 0.6,
    paramSchema: [
      { kind: 'color', key: 'color', label: 'Colour', default: '#cfd2d6' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'steel',
        options: [
          { value: 'steel', label: 'Stainless steel' },
          { value: 'matte', label: 'Matte' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 0,
        max: 1.2,
        step: 0.05,
        default: 0,
        unit: 'm',
      },
    ],
  },
  dishwasher: {
    kind: 'parametric',
    id: 'dishwasher',
    name: 'Dishwasher',
    category: 'appliances',
    keywords: ['dish washer', 'kitchen', 'built-in', 'integrated'],
    primitive: 'Dishwasher',
    defaultFootprint: { w: 0.6, d: 0.6, h: 0.85 },
    frontClearance: 0.6,
    paramSchema: [
      { kind: 'color', key: 'color', label: 'Colour', default: '#d7dadd' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'steel',
        options: [
          { value: 'steel', label: 'Stainless steel' },
          { value: 'matte', label: 'Matte' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      {
        kind: 'enum',
        key: 'integrated',
        label: 'Integrated',
        default: 'no',
        options: [
          { value: 'no', label: 'Visible controls' },
          { value: 'yes', label: 'Panel-ready' },
        ],
      },
    ],
  },
  'ceiling-fan': {
    kind: 'parametric',
    id: 'ceiling-fan',
    name: 'Ceiling fan',
    keywords: ['fan'],
    category: 'appliances',
    primitive: 'CeilingFan',
    defaultFootprint: { w: 1.3, d: 1.3, h: 0.4 },
    mounted: true,
    verticalSpan: { base: 2.1, top: 2.7 },
    paramSchema: [
      { kind: 'integer', key: 'blades', label: 'Blades', min: 2, max: 5, default: 3 },
      {
        kind: 'number',
        key: 'span',
        label: 'Span',
        min: 0.9,
        max: 1.6,
        step: 0.05,
        default: 1.3,
        unit: 'm',
      },
      { kind: 'color', key: 'bladeColor', label: 'Blades colour', default: '#6b4f34' },
    ],
  },
} satisfies Record<string, FurnitureDef>
