import type { FurnitureDef } from '../types'

/** bathroom furniture definitions. Part of the built-in catalog (see ../builtinCatalog.ts). */
export const BATHROOM_DEFS = {
  // ── Bathroom ────────────────────────────────────────────────────────────
  toilet: {
    kind: 'parametric',
    id: 'toilet',
    name: 'Toilet (WC)',
    keywords: ['wc', 'water closet', 'loo', 'commode'],
    category: 'bathroom',
    primitive: 'Toilet',
    defaultFootprint: { w: 0.4, d: 0.66, h: 0.78 },
    paramSchema: [
      { kind: 'color', key: 'color', label: 'Finish', default: '#f4f4f1' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'close-coupled',
        options: [
          { value: 'close-coupled', label: 'Close-coupled' },
          { value: 'wall-hung', label: 'Wall-hung' },
        ],
      },
    ],
  },
  'bathroom-sink': {
    kind: 'parametric',
    id: 'bathroom-sink',
    name: 'Basin',
    keywords: ['washbasin', 'wash basin', 'vanity', 'sink'],
    category: 'bathroom',
    primitive: 'BathroomSink',
    defaultFootprint: { w: 0.62, d: 0.5, h: 0.98 },
    paramSchema: [
      { kind: 'color', key: 'color', label: 'Basin', default: '#f4f4f1' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'pedestal',
        options: [
          { value: 'pedestal', label: 'Pedestal' },
          { value: 'vanity', label: 'Vanity cabinet' },
          { value: 'wall-hung', label: 'Wall-hung' },
        ],
      },
      { kind: 'color', key: 'cabinetColor', label: 'Cabinet (vanity)', default: '#8a6b48' },
      {
        kind: 'enum',
        key: 'cabinetFinish',
        label: 'Cabinet finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
    ],
  },
  bathtub: {
    kind: 'parametric',
    id: 'bathtub',
    name: 'Bathtub',
    category: 'bathroom',
    keywords: ['tub', 'soaker', 'bath'],
    primitive: 'Bathtub',
    defaultFootprint: { w: 1.6, d: 0.75, h: 0.58 },
    footprintParams: { w: 'width', d: 'depth' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Length',
        min: 1.3,
        max: 1.9,
        step: 0.05,
        default: 1.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Width',
        min: 0.65,
        max: 0.85,
        step: 0.02,
        default: 0.75,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'builtin',
        options: [
          { value: 'builtin', label: 'Built-in (alcove)' },
          { value: 'freestanding', label: 'Freestanding' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Tub', default: '#f3f1ec' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'gloss',
        options: [
          { value: 'gloss', label: 'Glossy acrylic' },
          { value: 'painted', label: 'Matte' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.4 },
    ],
  },
  shower: {
    kind: 'parametric',
    id: 'shower',
    name: 'Shower',
    keywords: ['shower stall', 'shower cubicle'],
    category: 'bathroom',
    primitive: 'Shower',
    defaultFootprint: { w: 0.9, d: 0.9, h: 2.0 },
    paramSchema: [
      {
        kind: 'number',
        key: 'size',
        label: 'Size',
        min: 0.8,
        max: 1.2,
        step: 0.05,
        default: 0.9,
        unit: 'm',
      },
      { kind: 'color', key: 'trayColor', label: 'Tray', default: '#eceae6' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Enclosure',
        default: 'corner',
        options: [
          { value: 'corner', label: 'Corner (2 panels)' },
          { value: 'walkin', label: 'Walk-in screen' },
        ],
      },
    ],
  },
  'towel-rail': {
    kind: 'parametric',
    id: 'towel-rail',
    name: 'Towel rail',
    category: 'bathroom',
    primitive: 'TowelRail',
    defaultFootprint: { w: 0.6, d: 0.14, h: 0.5 },
    footprintParams: { w: 'width' },
    mounted: true,
    verticalSpan: { base: 0.7, top: 1.2 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.4,
        max: 0.9,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Height',
        min: 0.8,
        max: 1.5,
        step: 0.05,
        default: 1.1,
        unit: 'm',
      },
      { kind: 'color', key: 'towelColor', label: 'Towel', default: '#d9e2e6' },
    ],
  },
  'towel-ladder': {
    kind: 'parametric',
    id: 'towel-ladder',
    name: 'Towel ladder (heated)',
    category: 'bathroom',
    primitive: 'TowelLadder',
    defaultFootprint: { w: 0.5, d: 0.28, h: 1.5 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.35,
        max: 0.7,
        step: 0.05,
        default: 0.5,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 1.0,
        max: 1.8,
        step: 0.05,
        default: 1.5,
        unit: 'm',
      },
      { kind: 'integer', key: 'bars', label: 'Rungs', min: 3, max: 8, default: 5 },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'chrome',
        options: [
          { value: 'chrome', label: 'Chrome' },
          { value: 'black', label: 'Black' },
          { value: 'brass', label: 'Brass' },
          { value: 'wood', label: 'Wood' },
        ],
      },
      {
        kind: 'enum',
        key: 'towel',
        label: 'Towels',
        default: 'yes',
        options: [
          { value: 'yes', label: 'Draped' },
          { value: 'no', label: 'Bare' },
        ],
      },
      { kind: 'color', key: 'towelColor', label: 'Towel', default: '#e8e3d8' },
    ],
  },
  'bathroom-mirror': {
    kind: 'parametric',
    id: 'bathroom-mirror',
    name: 'Mirror',
    keywords: ['vanity mirror'],
    category: 'bathroom',
    primitive: 'Mirror',
    defaultFootprint: { w: 0.6, d: 0.06, h: 0.9 },
    mounted: true,
    verticalSpan: { base: 1.0, top: 2.0 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.4,
        max: 1.2,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.5,
        max: 1.2,
        step: 0.05,
        default: 0.9,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Hang height',
        min: 1.1,
        max: 1.8,
        step: 0.05,
        default: 1.5,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'rect',
        options: [
          { value: 'rect', label: 'Rectangular' },
          { value: 'round', label: 'Round' },
          { value: 'frameless', label: 'Frameless' },
        ],
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#c9ccd1' },
    ],
  },
} satisfies Record<string, FurnitureDef>
