import type { FurnitureDef } from '../types'

/** beds furniture definitions. Part of the built-in catalog (see ../builtinCatalog.ts). */
export const BEDS_DEFS = {
  // ── Beds ────────────────────────────────────────────────────────────────
  // Beds use fixed Singapore-standard mattress sizes — width/length are
  // not user-editable, so they're omitted from paramSchema and resolved
  // from defaultFootprint via defaultParamProps().
  'bed-single': {
    kind: 'parametric',
    id: 'bed-single',
    name: 'Single bed',
    category: 'beds',
    primitive: 'Bed',
    defaultFootprint: { w: 0.91, d: 1.9, h: 0.6 },
    paramSchema: [
      { kind: 'color', key: 'mattressColor', label: 'Mattress', default: '#e8e2d4' },
      { kind: 'color', key: 'beddingColor', label: 'Bedding', default: '#c9d3da' },
      { kind: 'color', key: 'pillowColor', label: 'Pillows', default: '#fbfaf6' },
      { kind: 'color', key: 'throwColor', label: 'Throw', default: '#b08968' },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#6f553f' },
      {
        kind: 'enum',
        key: 'frameFinish',
        label: 'Frame finish',
        default: 'mat:floor-wood-oak',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      {
        kind: 'enum',
        key: 'headboardStyle',
        label: 'Headboard',
        default: 'flat',
        options: [
          { value: 'flat', label: 'Flat' },
          { value: 'paneled', label: 'Paneled' },
          { value: 'upholstered', label: 'Upholstered' },
        ],
      },
      {
        kind: 'enum',
        key: 'baseStyle',
        label: 'Base',
        default: 'standard',
        options: [
          { value: 'standard', label: 'Standard frame' },
          { value: 'platform', label: 'Platform' },
          { value: 'storage', label: 'Storage drawers' },
        ],
      },
      {
        kind: 'enum',
        key: 'beddingPattern',
        label: 'Bedding weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'bed-double': {
    kind: 'parametric',
    id: 'bed-double',
    name: 'Double bed',
    keywords: ['full bed', 'matrimonial bed'],
    category: 'beds',
    primitive: 'Bed',
    defaultFootprint: { w: 1.37, d: 1.9, h: 0.6 },
    paramSchema: [
      { kind: 'color', key: 'mattressColor', label: 'Mattress', default: '#e8e2d4' },
      { kind: 'color', key: 'beddingColor', label: 'Bedding', default: '#c9d3da' },
      { kind: 'color', key: 'pillowColor', label: 'Pillows', default: '#fbfaf6' },
      { kind: 'color', key: 'throwColor', label: 'Throw', default: '#b08968' },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#6f553f' },
      {
        kind: 'enum',
        key: 'frameFinish',
        label: 'Frame finish',
        default: 'mat:floor-wood-oak',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      {
        kind: 'enum',
        key: 'headboardStyle',
        label: 'Headboard',
        default: 'flat',
        options: [
          { value: 'flat', label: 'Flat' },
          { value: 'paneled', label: 'Paneled' },
          { value: 'upholstered', label: 'Upholstered' },
        ],
      },
      {
        kind: 'enum',
        key: 'baseStyle',
        label: 'Base',
        default: 'standard',
        options: [
          { value: 'standard', label: 'Standard frame' },
          { value: 'platform', label: 'Platform' },
          { value: 'storage', label: 'Storage drawers' },
        ],
      },
      {
        kind: 'enum',
        key: 'beddingPattern',
        label: 'Bedding weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'bed-queen': {
    kind: 'parametric',
    id: 'bed-queen',
    name: 'Queen bed',
    category: 'beds',
    primitive: 'Bed',
    defaultFootprint: { w: 1.52, d: 1.9, h: 0.6 },
    paramSchema: [
      { kind: 'color', key: 'mattressColor', label: 'Mattress', default: '#e8e2d4' },
      { kind: 'color', key: 'beddingColor', label: 'Bedding', default: '#c9d3da' },
      { kind: 'color', key: 'pillowColor', label: 'Pillows', default: '#fbfaf6' },
      { kind: 'color', key: 'throwColor', label: 'Throw', default: '#b08968' },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#6f553f' },
      {
        kind: 'enum',
        key: 'frameFinish',
        label: 'Frame finish',
        default: 'mat:floor-wood-oak',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      {
        kind: 'enum',
        key: 'headboardStyle',
        label: 'Headboard',
        default: 'paneled',
        options: [
          { value: 'flat', label: 'Flat' },
          { value: 'paneled', label: 'Paneled' },
          { value: 'upholstered', label: 'Upholstered' },
        ],
      },
      {
        kind: 'enum',
        key: 'baseStyle',
        label: 'Base',
        default: 'standard',
        options: [
          { value: 'standard', label: 'Standard frame' },
          { value: 'platform', label: 'Platform' },
          { value: 'storage', label: 'Storage drawers' },
        ],
      },
      {
        kind: 'enum',
        key: 'beddingPattern',
        label: 'Bedding weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'bed-king': {
    kind: 'parametric',
    id: 'bed-king',
    name: 'King bed',
    category: 'beds',
    primitive: 'Bed',
    defaultFootprint: { w: 1.82, d: 2.03, h: 0.6 },
    paramSchema: [
      { kind: 'color', key: 'mattressColor', label: 'Mattress', default: '#e8e2d4' },
      { kind: 'color', key: 'beddingColor', label: 'Bedding', default: '#c9d3da' },
      { kind: 'color', key: 'pillowColor', label: 'Pillows', default: '#fbfaf6' },
      { kind: 'color', key: 'throwColor', label: 'Throw', default: '#b08968' },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#6f553f' },
      {
        kind: 'enum',
        key: 'frameFinish',
        label: 'Frame finish',
        default: 'mat:floor-wood-oak',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      {
        kind: 'enum',
        key: 'headboardStyle',
        label: 'Headboard',
        default: 'paneled',
        options: [
          { value: 'flat', label: 'Flat' },
          { value: 'paneled', label: 'Paneled' },
          { value: 'upholstered', label: 'Upholstered' },
        ],
      },
      {
        kind: 'enum',
        key: 'baseStyle',
        label: 'Base',
        default: 'standard',
        options: [
          { value: 'standard', label: 'Standard frame' },
          { value: 'platform', label: 'Platform' },
          { value: 'storage', label: 'Storage drawers' },
        ],
      },
      {
        kind: 'enum',
        key: 'beddingPattern',
        label: 'Bedding weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'bunk-bed': {
    kind: 'parametric',
    id: 'bunk-bed',
    name: 'Bunk bed',
    category: 'beds',
    primitive: 'BunkBed',
    defaultFootprint: { w: 0.95, d: 1.95, h: 1.62 },
    paramSchema: [
      { kind: 'color', key: 'lowerBedding', label: 'Lower bedding', default: '#c9d3da' },
      { kind: 'color', key: 'upperBedding', label: 'Upper bedding', default: '#d9c3b0' },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#b8895a' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Frame finish',
        default: 'mat:floor-wood-oak',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
} satisfies Record<string, FurnitureDef>
