import type { FurnitureDef } from '../types'

/** decor furniture definitions. Part of the built-in catalog (see ../builtinCatalog.ts). */
export const DECOR_DEFS = {
  'feature-wall': {
    kind: 'parametric',
    id: 'feature-wall',
    name: 'Feature wall (fluted)',
    category: 'decor',
    primitive: 'FeatureWall',
    defaultFootprint: { w: 1.8, d: 0.08, h: 2.5 },
    footprintParams: { w: 'width' },
    mounted: true,
    // A flush wall treatment — never blocks placing furniture in front of it.
    noClip: true,
    verticalSpan: { base: 0, top: 2.6 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.8,
        max: 3.4,
        step: 0.1,
        default: 1.8,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 2.0,
        max: 2.7,
        step: 0.05,
        default: 2.5,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#8a6b48' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Profile',
        default: 'fluted',
        options: [
          { value: 'fluted', label: 'Fluted (half-round)' },
          { value: 'slat', label: 'Slat (square)' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'room-divider': {
    kind: 'parametric',
    id: 'room-divider',
    name: 'Room divider',
    category: 'decor',
    keywords: ['screen', 'partition', 'privacy screen', 'slat screen'],
    primitive: 'RoomDivider',
    defaultFootprint: { w: 1.6, d: 0.06, h: 2.0 },
    footprintParams: { w: 'width' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.8,
        max: 3.0,
        step: 0.1,
        default: 1.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 1.2,
        max: 2.4,
        step: 0.1,
        default: 2.0,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'slat',
        options: [
          { value: 'slat', label: 'Vertical slats' },
          { value: 'fluted', label: 'Fluted panel' },
          { value: 'grid', label: 'Grid lattice' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#7a5c3c' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  // ── Decor ───────────────────────────────────────────────────────────────
  'tabletop-decor': {
    kind: 'parametric',
    id: 'tabletop-decor',
    name: 'Decor set',
    category: 'decor',
    primitive: 'TabletopDecor',
    defaultFootprint: { w: 0.34, d: 0.22, h: 0.22 },
    verticalSpan: { base: 0.42, top: 0.66 },
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.2,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      { kind: 'color', key: 'bookColor', label: 'Books', default: '#8a5a3c' },
      { kind: 'color', key: 'vaseColor', label: 'Vase', default: '#cfd3d6' },
    ],
  },
  'roller-blind': {
    kind: 'parametric',
    id: 'roller-blind',
    name: 'Roller blind',
    keywords: ['blinds', 'window shade', 'shade'],
    category: 'decor',
    primitive: 'RollerBlind',
    defaultFootprint: { w: 1.2, d: 0.12, h: 2.3 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.6,
        max: 2.6,
        step: 0.1,
        default: 1.2,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Top height',
        min: 1.8,
        max: 2.5,
        step: 0.05,
        default: 2.3,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'drop',
        label: 'Drop',
        min: 0.4,
        max: 2.2,
        step: 0.1,
        default: 1.7,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Fabric', default: '#d8d2c4' },
      {
        kind: 'enum',
        key: 'kind',
        label: 'Type',
        default: 'roller',
        options: [
          { value: 'roller', label: 'Roller' },
          { value: 'venetian', label: 'Venetian slats' },
        ],
      },
    ],
  },
  'hanging-plant': {
    kind: 'parametric',
    id: 'hanging-plant',
    name: 'Hanging plant',
    category: 'decor',
    keywords: ['trailing', 'pothos', 'ceiling plant', 'macrame'],
    primitive: 'HangingPlant',
    defaultFootprint: { w: 0.36, d: 0.36, h: 0.5 },
    mounted: true,
    verticalSpan: { base: 1.6, top: 2.5 },
    paramSchema: [
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Hang from',
        min: 2.0,
        max: 2.6,
        step: 0.05,
        default: 2.45,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'drop',
        label: 'Cord drop',
        min: 0.2,
        max: 0.8,
        step: 0.05,
        default: 0.4,
        unit: 'm',
      },
      { kind: 'color', key: 'potColor', label: 'Pot', default: '#cdbb9a' },
      { kind: 'color', key: 'leafColor', label: 'Foliage', default: '#4a7a44' },
      {
        kind: 'enum',
        key: 'size',
        label: 'Size',
        default: 'medium',
        options: [
          { value: 'medium', label: 'Medium' },
          { value: 'large', label: 'Large' },
        ],
      },
    ],
  },
  'floor-vase': {
    kind: 'parametric',
    id: 'floor-vase',
    name: 'Floor vase',
    category: 'decor',
    keywords: ['vase', 'pampas', 'stems', 'urn'],
    primitive: 'FloorVase',
    defaultFootprint: { w: 0.44, d: 0.44, h: 1.25 },
    verticalSpan: { base: 0, top: 1.4 },
    paramSchema: [
      {
        kind: 'number',
        key: 'height',
        label: 'Vase height',
        min: 0.4,
        max: 1.0,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'tall',
        options: [
          { value: 'tall', label: 'Tall taper' },
          { value: 'round', label: 'Round belly' },
          { value: 'wide', label: 'Wide' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Vase', default: '#d8cfc0' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'gloss',
        options: [
          { value: 'gloss', label: 'Glazed' },
          { value: 'painted', label: 'Matte' },
          { value: 'wood', label: 'Stoneware' },
        ],
      },
      {
        kind: 'enum',
        key: 'stems',
        label: 'Stems',
        default: 'pampas',
        options: [
          { value: 'pampas', label: 'Pampas' },
          { value: 'branch', label: 'Branches' },
          { value: 'none', label: 'Empty' },
        ],
      },
      { kind: 'color', key: 'stemColor', label: 'Stems', default: '#cdbb93' },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.3 },
    ],
  },
  'wall-mirror': {
    kind: 'parametric',
    id: 'wall-mirror',
    name: 'Wall mirror',
    category: 'decor',
    keywords: ['mirror', 'round mirror', 'statement mirror'],
    primitive: 'WallMirror',
    defaultFootprint: { w: 0.7, d: 0.06, h: 1.0 },
    footprintParams: { w: 'width' },
    mounted: true,
    verticalSpan: { base: 0.9, top: 2.05 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.4,
        max: 1.2,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.4,
        max: 1.6,
        step: 0.05,
        default: 1.0,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Hang height',
        min: 0.9,
        max: 1.9,
        step: 0.05,
        default: 1.5,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'round',
        options: [
          { value: 'round', label: 'Round' },
          { value: 'arch', label: 'Arched' },
          { value: 'rect', label: 'Rectangle' },
        ],
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#caa46a' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Frame finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Metal/Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.2 },
    ],
  },
  'wall-art': {
    kind: 'parametric',
    id: 'wall-art',
    name: 'Wall art',
    keywords: ['painting', 'picture', 'poster', 'print', 'framed art'],
    category: 'decor',
    primitive: 'WallArt',
    defaultFootprint: { w: 0.8, d: 0.08, h: 0.6 },
    mounted: true,
    verticalSpan: { base: 1.1, top: 2.0 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.3,
        max: 1.6,
        step: 0.05,
        default: 0.8,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.3,
        max: 1.2,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Hang height',
        min: 1.0,
        max: 2.0,
        step: 0.05,
        default: 1.55,
        unit: 'm',
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#2c2722' },
      { kind: 'color', key: 'artColor', label: 'Art', default: '#9fb0a6' },
      {
        kind: 'enum',
        key: 'frameStyle',
        label: 'Frame style',
        default: 'thin',
        options: [
          { value: 'thin', label: 'Thin' },
          { value: 'gallery', label: 'Gallery (wide)' },
          { value: 'box', label: 'Box float' },
          { value: 'none', label: 'Frameless' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Print',
        default: 'solid',
        options: [
          { value: 'solid', label: 'Solid' },
          { value: 'gradient', label: 'Gradient' },
          { value: 'stripes', label: 'Stripes' },
          { value: 'blocks', label: 'Colour blocks' },
          { value: 'chevron', label: 'Chevron' },
        ],
      },
      { kind: 'color', key: 'artColor2', label: 'Art 2 (accent)', default: '#d8c7a0' },
    ],
  },
  'wall-clock': {
    kind: 'parametric',
    id: 'wall-clock',
    name: 'Wall clock',
    keywords: ['clock'],
    category: 'decor',
    primitive: 'WallClock',
    defaultFootprint: { w: 0.32, d: 0.05, h: 0.32 },
    mounted: true,
    verticalSpan: { base: 1.35, top: 1.85 },
    paramSchema: [
      {
        kind: 'number',
        key: 'diameter',
        label: 'Diameter',
        min: 0.2,
        max: 0.6,
        step: 0.02,
        default: 0.32,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Hang height',
        min: 1.2,
        max: 2.2,
        step: 0.05,
        default: 1.6,
        unit: 'm',
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#2a2722' },
      { kind: 'color', key: 'faceColor', label: 'Face', default: '#f4f1ea' },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'round',
        options: [
          { value: 'round', label: 'Round' },
          { value: 'square', label: 'Square' },
        ],
      },
      {
        kind: 'enum',
        key: 'markers',
        label: 'Markers',
        default: 'four',
        options: [
          { value: 'four', label: 'Quarter ticks' },
          { value: 'twelve', label: 'All hours' },
        ],
      },
    ],
  },
  'wall-shelf': {
    kind: 'parametric',
    id: 'wall-shelf',
    name: 'Wall shelf',
    category: 'decor',
    primitive: 'WallShelf',
    defaultFootprint: { w: 0.8, d: 0.22, h: 0.15 },
    footprintParams: { w: 'width', d: 'depth' },
    mounted: true,
    verticalSpan: { base: 1.3, top: 1.5 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.4,
        max: 1.6,
        step: 0.05,
        default: 0.8,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.16,
        max: 0.32,
        step: 0.02,
        default: 0.22,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 0.8,
        max: 2.0,
        step: 0.05,
        default: 1.4,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#8a6b48' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'bracket',
        options: [
          { value: 'bracket', label: 'L-bracket' },
          { value: 'floating', label: 'Floating' },
          { value: 'twotier', label: 'Two-tier' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'floor-mirror': {
    kind: 'parametric',
    id: 'floor-mirror',
    name: 'Floor mirror',
    category: 'decor',
    primitive: 'FloorMirror',
    defaultFootprint: { w: 0.6, d: 0.22, h: 1.6 },
    footprintParams: { w: 'width' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.4,
        max: 0.9,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 1.2,
        max: 2.0,
        step: 0.05,
        default: 1.6,
        unit: 'm',
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#6f553f' },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'rect',
        options: [
          { value: 'rect', label: 'Rectangular (leaning)' },
          { value: 'round', label: 'Round (cheval stand)' },
        ],
      },
      {
        kind: 'enum',
        key: 'frameFinish',
        label: 'Frame finish',
        default: 'mat:floor-wood-oak',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  aquarium: {
    kind: 'parametric',
    id: 'aquarium',
    name: 'Aquarium',
    keywords: ['fish tank', 'fish', 'tank', 'vivarium', 'aquascape'],
    category: 'decor',
    primitive: 'Aquarium',
    defaultFootprint: { w: 0.9, d: 0.42, h: 1.12 },
    footprintParams: { w: 'width' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.5,
        max: 1.6,
        step: 0.05,
        default: 0.9,
        unit: 'm',
      },
      { kind: 'color', key: 'standColor', label: 'Stand', default: '#3a2f26' },
      {
        kind: 'enum',
        key: 'standFinish',
        label: 'Stand finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'color', key: 'waterColor', label: 'Water tint', default: '#3f7d8c' },
    ],
  },
  'pet-bed': {
    kind: 'parametric',
    id: 'pet-bed',
    name: 'Pet bed',
    keywords: ['dog bed', 'cat bed', 'pet', 'basket', 'dog', 'cat'],
    category: 'decor',
    primitive: 'PetBed',
    defaultFootprint: { w: 0.7, d: 0.7, h: 0.22 },
    footprintParams: { w: 'size', d: 'size' },
    paramSchema: [
      {
        kind: 'number',
        key: 'size',
        label: 'Size',
        min: 0.45,
        max: 1.1,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'round',
        options: [
          { value: 'round', label: 'Round basket' },
          { value: 'rect', label: 'Rectangular mat' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Bolster', default: '#9b6f52' },
      { kind: 'color', key: 'cushion', label: 'Cushion', default: '#d8c9b0' },
    ],
  },
  'potted-plant': {
    kind: 'parametric',
    id: 'potted-plant',
    name: 'Potted plant',
    keywords: ['plant', 'houseplant', 'greenery', 'pot plant'],
    category: 'decor',
    primitive: 'PottedPlant',
    defaultFootprint: { w: 0.55, d: 0.55, h: 1.0 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'type',
        label: 'Type',
        default: 'bush',
        options: [
          { value: 'bush', label: 'Bush' },
          { value: 'snake', label: 'Snake plant' },
          { value: 'palm', label: 'Palm' },
          { value: 'fiddle', label: 'Fiddle-leaf fig' },
        ],
      },
      {
        kind: 'enum',
        key: 'potShape',
        label: 'Planter',
        default: 'tapered',
        options: [
          { value: 'tapered', label: 'Tapered' },
          { value: 'cylinder', label: 'Cylinder' },
          { value: 'square', label: 'Square box' },
        ],
      },
      {
        kind: 'enum',
        key: 'size',
        label: 'Size',
        default: 'medium',
        options: [
          { value: 'small', label: 'Small' },
          { value: 'medium', label: 'Medium' },
          { value: 'large', label: 'Large' },
        ],
      },
      { kind: 'color', key: 'potColor', label: 'Pot', default: '#b9743f' },
      { kind: 'color', key: 'leafColor', label: 'Foliage', default: '#3f6b3a' },
    ],
  },
  fireplace: {
    kind: 'parametric',
    id: 'fireplace',
    name: 'Electric fireplace',
    category: 'decor',
    keywords: ['fire', 'hearth', 'flame', 'mantel'],
    primitive: 'Fireplace',
    defaultFootprint: { w: 1.2, d: 0.34, h: 0.6 },
    footprintParams: { w: 'width' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.8,
        max: 1.8,
        step: 0.1,
        default: 1.2,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'wall',
        options: [
          { value: 'wall', label: 'Wall-mounted' },
          { value: 'console', label: 'Console + mantel' },
        ],
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 0.6,
        max: 1.4,
        step: 0.05,
        default: 1.0,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Surround', default: '#23242a' },
      { kind: 'color', key: 'flameColor', label: 'Flame', default: '#ff7a1a' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'gloss',
        options: [
          { value: 'gloss', label: 'Gloss' },
          { value: 'painted', label: 'Matte' },
          { value: 'wood', label: 'Wood' },
        ],
      },
    ],
  },
  piano: {
    kind: 'parametric',
    id: 'piano',
    name: 'Piano',
    category: 'decor',
    keywords: ['upright', 'digital piano', 'keyboard', 'music'],
    primitive: 'Piano',
    defaultFootprint: { w: 1.45, d: 0.6, h: 1.28 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'upright',
        options: [
          { value: 'upright', label: 'Upright' },
          { value: 'digital', label: 'Digital console' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Body', default: '#23211f' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'gloss',
        options: [
          { value: 'gloss', label: 'Polished' },
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Matte' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.6 },
    ],
  },
} satisfies Record<string, FurnitureDef>
