import type { FurnitureDef } from '../types'

/** decor furniture definitions. Part of the built-in catalog (see ../builtinCatalog.ts). */
export const DECOR_DEFS = {
  'feature-wall': {
    kind: 'parametric',
    id: 'feature-wall',
    name: 'Feature wall (fluted)',
    category: 'decor',
    primitive: 'FeatureWall',
    defaultFootprint: { w: 1.8, d: 0.08, h: 2.5 },
    footprintParams: { w: 'width' },
    mounted: true,
    // A flush wall treatment — never blocks placing furniture in front of it.
    noClip: true,
    verticalSpan: { base: 0, top: 2.6 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.8,
        max: 3.4,
        step: 0.1,
        default: 1.8,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 2.0,
        max: 2.7,
        step: 0.05,
        default: 2.5,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#8a6b48' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Profile',
        default: 'fluted',
        options: [
          { value: 'fluted', label: 'Fluted (half-round)' },
          { value: 'slat', label: 'Slat (square)' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'room-divider': {
    kind: 'parametric',
    id: 'room-divider',
    name: 'Room divider',
    category: 'decor',
    keywords: ['screen', 'partition', 'privacy screen', 'slat screen'],
    primitive: 'RoomDivider',
    defaultFootprint: { w: 1.6, d: 0.06, h: 2.0 },
    footprintParams: { w: 'width' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.8,
        max: 3.0,
        step: 0.1,
        default: 1.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 1.2,
        max: 2.4,
        step: 0.1,
        default: 2.0,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'slat',
        options: [
          { value: 'slat', label: 'Vertical slats' },
          { value: 'fluted', label: 'Fluted panel' },
          { value: 'grid', label: 'Grid lattice' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#7a5c3c' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  // ── Decor ───────────────────────────────────────────────────────────────
  'tabletop-decor': {
    kind: 'parametric',
    id: 'tabletop-decor',
    name: 'Decor set',
    category: 'decor',
    primitive: 'TabletopDecor',
    defaultFootprint: { w: 0.34, d: 0.22, h: 0.22 },
    verticalSpan: { base: 0.42, top: 0.66 },
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.2,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      { kind: 'color', key: 'bookColor', label: 'Books', default: '#8a5a3c' },
      { kind: 'color', key: 'vaseColor', label: 'Vase', default: '#cfd3d6' },
    ],
  },
  'roller-blind': {
    kind: 'parametric',
    id: 'roller-blind',
    name: 'Roller blind',
    keywords: ['blinds', 'window shade', 'shade'],
    category: 'decor',
    primitive: 'RollerBlind',
    defaultFootprint: { w: 1.3, d: 0.12, h: 2.3 },
    noClip: true,
    // Window-bound: statically placed on a window (no move/rotate/flip). Placement
    // sizes the blind slightly wider than its window with a covering drop.
    windowBound: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.6,
        max: 2.8,
        step: 0.1,
        default: 1.3,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Top height',
        min: 1.8,
        max: 2.5,
        step: 0.05,
        default: 2.3,
        unit: 'm',
      },
      {
        // Maximum extent (m) the blind covers when fully lowered — placement sets
        // it to span the window.
        kind: 'number',
        key: 'drop',
        label: 'Drop',
        min: 0.4,
        max: 2.4,
        step: 0.1,
        default: 1.7,
        unit: 'm',
      },
      {
        // Raise/lower the blind with a smooth animation (BLIND-LOWER): 0 = raised
        // (rolled up, window exposed), 1 = lowered (covers the window). The
        // primitive eases between the two; window light attenuation can track it.
        kind: 'number',
        key: 'lower',
        label: 'Lower (open → closed)',
        min: 0,
        max: 1,
        step: 0.05,
        default: 1,
      },
      {
        // Fabric weave — fabric-only (a blind's shade is cloth); reuses the
        // shared tone-on-tone pattern set below. Applies to the roller panel.
        kind: 'enum',
        key: 'material',
        label: 'Fabric',
        default: 'cotton',
        options: [
          { value: 'cotton', label: 'Cotton' },
          { value: 'linen', label: 'Linen' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      {
        // Opacity / light-blocking (CURTAIN-OPACITY): sheer → blackout.
        kind: 'enum',
        key: 'lightBlock',
        label: 'Opacity',
        default: 'room',
        options: [
          { value: 'sheer', label: 'Sheer' },
          { value: 'light', label: 'Light-filtering' },
          { value: 'room', label: 'Room-darkening' },
          { value: 'blackout', label: 'Blackout' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Pattern',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#d8d2c4' },
      {
        kind: 'enum',
        key: 'kind',
        label: 'Type',
        default: 'roller',
        options: [
          { value: 'roller', label: 'Roller' },
          { value: 'venetian', label: 'Venetian slats' },
        ],
      },
    ],
  },
  'hanging-plant': {
    kind: 'parametric',
    id: 'hanging-plant',
    name: 'Hanging plant',
    category: 'decor',
    keywords: ['trailing', 'pothos', 'ceiling plant', 'macrame'],
    primitive: 'HangingPlant',
    defaultFootprint: { w: 0.36, d: 0.36, h: 0.5 },
    mounted: true,
    verticalSpan: { base: 1.6, top: 2.5 },
    paramSchema: [
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Hang from',
        min: 2.0,
        max: 2.6,
        step: 0.05,
        default: 2.45,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'drop',
        label: 'Cord drop',
        min: 0.2,
        max: 0.8,
        step: 0.05,
        default: 0.4,
        unit: 'm',
      },
      { kind: 'color', key: 'potColor', label: 'Pot', default: '#cdbb9a' },
      { kind: 'color', key: 'leafColor', label: 'Foliage', default: '#4a7a44' },
      {
        kind: 'enum',
        key: 'size',
        label: 'Size',
        default: 'medium',
        options: [
          { value: 'medium', label: 'Medium' },
          { value: 'large', label: 'Large' },
        ],
      },
    ],
  },
  'floor-vase': {
    kind: 'parametric',
    id: 'floor-vase',
    name: 'Floor vase',
    category: 'decor',
    keywords: ['vase', 'pampas', 'stems', 'urn'],
    primitive: 'FloorVase',
    defaultFootprint: { w: 0.44, d: 0.44, h: 1.25 },
    verticalSpan: { base: 0, top: 1.4 },
    paramSchema: [
      {
        kind: 'number',
        key: 'height',
        label: 'Vase height',
        min: 0.4,
        max: 1.0,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'tall',
        options: [
          { value: 'tall', label: 'Tall taper' },
          { value: 'round', label: 'Round belly' },
          { value: 'wide', label: 'Wide' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Vase', default: '#d8cfc0' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'gloss',
        options: [
          { value: 'gloss', label: 'Glazed' },
          { value: 'painted', label: 'Matte' },
          { value: 'wood', label: 'Stoneware' },
        ],
      },
      {
        kind: 'enum',
        key: 'stems',
        label: 'Stems',
        default: 'pampas',
        options: [
          { value: 'pampas', label: 'Pampas' },
          { value: 'branch', label: 'Branches' },
          { value: 'none', label: 'Empty' },
        ],
      },
      { kind: 'color', key: 'stemColor', label: 'Stems', default: '#cdbb93' },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.3 },
    ],
  },
  'wall-mirror': {
    kind: 'parametric',
    id: 'wall-mirror',
    name: 'Wall mirror',
    category: 'decor',
    keywords: ['mirror', 'round mirror', 'statement mirror'],
    primitive: 'WallMirror',
    defaultFootprint: { w: 0.7, d: 0.06, h: 1.0 },
    footprintParams: { w: 'width' },
    mounted: true,
    verticalSpan: { base: 0.9, top: 2.05 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.4,
        max: 1.2,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.4,
        max: 1.6,
        step: 0.05,
        default: 1.0,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Hang height',
        min: 0.9,
        max: 1.9,
        step: 0.05,
        default: 1.5,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'round',
        options: [
          { value: 'round', label: 'Round' },
          { value: 'arch', label: 'Arched' },
          { value: 'rect', label: 'Rectangle' },
        ],
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#caa46a' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Frame finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Metal/Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.2 },
    ],
  },
  'wall-art': {
    kind: 'parametric',
    id: 'wall-art',
    name: 'Wall art',
    keywords: ['painting', 'picture', 'poster', 'print', 'framed art'],
    category: 'decor',
    primitive: 'WallArt',
    defaultFootprint: { w: 0.8, d: 0.08, h: 0.6 },
    mounted: true,
    verticalSpan: { base: 1.1, top: 2.0 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.3,
        max: 1.6,
        step: 0.05,
        default: 0.8,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.3,
        max: 1.2,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Hang height',
        min: 1.0,
        max: 2.0,
        step: 0.05,
        default: 1.55,
        unit: 'm',
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#2c2722' },
      { kind: 'color', key: 'artColor', label: 'Art', default: '#9fb0a6' },
      {
        kind: 'enum',
        key: 'frameStyle',
        label: 'Frame style',
        default: 'thin',
        options: [
          { value: 'thin', label: 'Thin' },
          { value: 'gallery', label: 'Gallery (wide)' },
          { value: 'box', label: 'Box float' },
          { value: 'none', label: 'Frameless' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Print',
        default: 'solid',
        options: [
          { value: 'solid', label: 'Solid' },
          { value: 'gradient', label: 'Gradient' },
          { value: 'stripes', label: 'Stripes' },
          { value: 'blocks', label: 'Colour blocks' },
          { value: 'chevron', label: 'Chevron' },
        ],
      },
      { kind: 'color', key: 'artColor2', label: 'Art 2 (accent)', default: '#d8c7a0' },
    ],
  },
  'wall-clock': {
    kind: 'parametric',
    id: 'wall-clock',
    name: 'Wall clock',
    keywords: ['clock'],
    category: 'decor',
    primitive: 'WallClock',
    defaultFootprint: { w: 0.32, d: 0.05, h: 0.32 },
    mounted: true,
    verticalSpan: { base: 1.35, top: 1.85 },
    paramSchema: [
      {
        kind: 'number',
        key: 'diameter',
        label: 'Diameter',
        min: 0.2,
        max: 0.6,
        step: 0.02,
        default: 0.32,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Hang height',
        min: 1.2,
        max: 2.2,
        step: 0.05,
        default: 1.6,
        unit: 'm',
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#2a2722' },
      { kind: 'color', key: 'faceColor', label: 'Face', default: '#f4f1ea' },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'round',
        options: [
          { value: 'round', label: 'Round' },
          { value: 'square', label: 'Square' },
        ],
      },
      {
        kind: 'enum',
        key: 'markers',
        label: 'Markers',
        default: 'four',
        options: [
          { value: 'four', label: 'Quarter ticks' },
          { value: 'twelve', label: 'All hours' },
        ],
      },
    ],
  },
  'wall-shelf': {
    kind: 'parametric',
    id: 'wall-shelf',
    name: 'Wall shelf',
    category: 'decor',
    primitive: 'WallShelf',
    defaultFootprint: { w: 0.8, d: 0.22, h: 0.15 },
    footprintParams: { w: 'width', d: 'depth' },
    mounted: true,
    verticalSpan: { base: 1.3, top: 1.5 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.4,
        max: 1.6,
        step: 0.05,
        default: 0.8,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.16,
        max: 0.32,
        step: 0.02,
        default: 0.22,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 0.8,
        max: 2.0,
        step: 0.05,
        default: 1.4,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#8a6b48' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'bracket',
        options: [
          { value: 'bracket', label: 'L-bracket' },
          { value: 'floating', label: 'Floating' },
          { value: 'twotier', label: 'Two-tier' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'floor-mirror': {
    kind: 'parametric',
    id: 'floor-mirror',
    name: 'Floor mirror',
    category: 'decor',
    primitive: 'FloorMirror',
    defaultFootprint: { w: 0.6, d: 0.22, h: 1.6 },
    footprintParams: { w: 'width' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.4,
        max: 0.9,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 1.2,
        max: 2.0,
        step: 0.05,
        default: 1.6,
        unit: 'm',
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#6f553f' },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'rect',
        options: [
          { value: 'rect', label: 'Rectangular (leaning)' },
          { value: 'round', label: 'Round (cheval stand)' },
        ],
      },
      {
        kind: 'enum',
        key: 'frameFinish',
        label: 'Frame finish',
        default: 'mat:floor-wood-oak',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  aquarium: {
    kind: 'parametric',
    id: 'aquarium',
    name: 'Aquarium',
    keywords: ['fish tank', 'fish', 'tank', 'vivarium', 'aquascape'],
    category: 'decor',
    primitive: 'Aquarium',
    defaultFootprint: { w: 0.9, d: 0.42, h: 1.12 },
    footprintParams: { w: 'width' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.5,
        max: 1.6,
        step: 0.05,
        default: 0.9,
        unit: 'm',
      },
      { kind: 'color', key: 'standColor', label: 'Stand', default: '#3a2f26' },
      {
        kind: 'enum',
        key: 'standFinish',
        label: 'Stand finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'color', key: 'waterColor', label: 'Water tint', default: '#3f7d8c' },
    ],
  },
  'pet-bed': {
    kind: 'parametric',
    id: 'pet-bed',
    name: 'Pet bed',
    keywords: ['dog bed', 'cat bed', 'pet', 'basket', 'dog', 'cat'],
    category: 'decor',
    primitive: 'PetBed',
    defaultFootprint: { w: 0.7, d: 0.7, h: 0.22 },
    footprintParams: { w: 'size', d: 'size' },
    paramSchema: [
      {
        kind: 'number',
        key: 'size',
        label: 'Size',
        min: 0.45,
        max: 1.1,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'round',
        options: [
          { value: 'round', label: 'Round basket' },
          { value: 'rect', label: 'Rectangular mat' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Bolster', default: '#9b6f52' },
      { kind: 'color', key: 'cushion', label: 'Cushion', default: '#d8c9b0' },
    ],
  },
  'potted-plant': {
    kind: 'parametric',
    id: 'potted-plant',
    name: 'Potted plant',
    keywords: ['plant', 'houseplant', 'greenery', 'pot plant'],
    category: 'decor',
    primitive: 'PottedPlant',
    defaultFootprint: { w: 0.55, d: 0.55, h: 1.0 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'type',
        label: 'Type',
        default: 'bush',
        options: [
          { value: 'bush', label: 'Bush' },
          { value: 'snake', label: 'Snake plant' },
          { value: 'palm', label: 'Palm' },
          { value: 'fiddle', label: 'Fiddle-leaf fig' },
        ],
      },
      {
        kind: 'enum',
        key: 'potShape',
        label: 'Planter',
        default: 'tapered',
        options: [
          { value: 'tapered', label: 'Tapered' },
          { value: 'cylinder', label: 'Cylinder' },
          { value: 'square', label: 'Square box' },
        ],
      },
      {
        kind: 'enum',
        key: 'size',
        label: 'Size',
        default: 'medium',
        options: [
          { value: 'small', label: 'Small' },
          { value: 'medium', label: 'Medium' },
          { value: 'large', label: 'Large' },
        ],
      },
      { kind: 'color', key: 'potColor', label: 'Pot', default: '#b9743f' },
      { kind: 'color', key: 'leafColor', label: 'Foliage', default: '#3f6b3a' },
    ],
  },
  fireplace: {
    kind: 'parametric',
    id: 'fireplace',
    name: 'Electric fireplace',
    category: 'decor',
    keywords: ['fire', 'hearth', 'flame', 'mantel'],
    primitive: 'Fireplace',
    defaultFootprint: { w: 1.2, d: 0.34, h: 0.6 },
    footprintParams: { w: 'width' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.8,
        max: 1.8,
        step: 0.1,
        default: 1.2,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'wall',
        options: [
          { value: 'wall', label: 'Wall-mounted' },
          { value: 'console', label: 'Console + mantel' },
        ],
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 0.6,
        max: 1.4,
        step: 0.05,
        default: 1.0,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Surround', default: '#23242a' },
      { kind: 'color', key: 'flameColor', label: 'Flame', default: '#ff7a1a' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'gloss',
        options: [
          { value: 'gloss', label: 'Gloss' },
          { value: 'painted', label: 'Matte' },
          { value: 'wood', label: 'Wood' },
        ],
      },
    ],
  },
  piano: {
    kind: 'parametric',
    id: 'piano',
    name: 'Piano',
    category: 'decor',
    keywords: ['upright', 'digital piano', 'keyboard', 'music'],
    primitive: 'Piano',
    defaultFootprint: { w: 1.45, d: 0.6, h: 1.28 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'upright',
        options: [
          { value: 'upright', label: 'Upright' },
          { value: 'digital', label: 'Digital console' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Body', default: '#23211f' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'gloss',
        options: [
          { value: 'gloss', label: 'Polished' },
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Matte' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.6 },
    ],
  },
  // ── Set-dressing / styling props ────────────────────────────────────────
  'book-stack': {
    kind: 'parametric',
    id: 'book-stack',
    name: 'Book stack',
    keywords: ['books', 'stacked books', 'leaning books', 'shelf books', 'reading'],
    category: 'decor',
    primitive: 'BookStack',
    defaultFootprint: { w: 0.32, d: 0.16, h: 0.22 },
    verticalSpan: { base: 0.42, top: 0.64 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.2,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      { kind: 'color', key: 'spineColor', label: 'Spine 1', default: '#7a4028' },
      { kind: 'color', key: 'accentColor', label: 'Spine 2', default: '#3b5a6b' },
    ],
  },
  'throw-cushion': {
    kind: 'parametric',
    id: 'throw-cushion',
    name: 'Throw cushion',
    keywords: ['cushion', 'scatter cushion', 'pillow', 'sofa pillow', 'accent pillow'],
    category: 'decor',
    primitive: 'ThrowCushion',
    defaultFootprint: { w: 0.45, d: 0.45, h: 0.15 },
    verticalSpan: { base: 0.52, top: 0.67 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.0,
        step: 0.02,
        default: 0.52,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Fabric', default: '#b08068' },
      { kind: 'color', key: 'accentColor', label: 'Border', default: '#7a5a48' },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'square',
        options: [
          { value: 'square', label: 'Square' },
          { value: 'rect', label: 'Rectangular' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Fabric',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'stripe', label: 'Stripe' },
        ],
      },
    ],
  },
  'throw-blanket': {
    kind: 'parametric',
    id: 'throw-blanket',
    name: 'Throw blanket',
    keywords: ['throw', 'blanket', 'folded blanket', 'couch throw', 'bed throw'],
    category: 'decor',
    primitive: 'ThrowBlanket',
    defaultFootprint: { w: 0.46, d: 0.32, h: 0.16 },
    verticalSpan: { base: 0.52, top: 0.68 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.0,
        step: 0.02,
        default: 0.52,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Fabric main', default: '#c4b49a' },
      { kind: 'color', key: 'accentColor', label: 'Fabric back', default: '#a89278' },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'stripe', label: 'Stripe' },
          { value: 'herringbone', label: 'Herringbone' },
        ],
      },
    ],
  },
  'candle-cluster': {
    kind: 'parametric',
    id: 'candle-cluster',
    name: 'Candle cluster',
    keywords: ['candles', 'pillar candles', 'taper candles', 'lantern', 'candleholder'],
    category: 'decor',
    primitive: 'CandleCluster',
    defaultFootprint: { w: 0.28, d: 0.28, h: 0.2 },
    verticalSpan: { base: 0.42, top: 0.62 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.2,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      { kind: 'color', key: 'waxColor', label: 'Wax', default: '#f5f0e8' },
      { kind: 'color', key: 'plateColor', label: 'Base plate', default: '#c8c0b0' },
      {
        kind: 'enum',
        key: 'flame',
        label: 'Flame',
        default: 'yes',
        options: [
          { value: 'yes', label: 'Lit' },
          { value: 'no', label: 'Unlit' },
        ],
      },
    ],
  },
  'fruit-bowl': {
    kind: 'parametric',
    id: 'fruit-bowl',
    name: 'Fruit bowl',
    keywords: ['bowl', 'decorative bowl', 'centrepiece', 'ceramic bowl', 'fruit'],
    category: 'decor',
    primitive: 'FruitBowl',
    defaultFootprint: { w: 0.32, d: 0.32, h: 0.14 },
    verticalSpan: { base: 0.42, top: 0.56 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.2,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      { kind: 'color', key: 'bowlColor', label: 'Bowl', default: '#c8b89a' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'gloss',
        options: [
          { value: 'gloss', label: 'Glazed' },
          { value: 'painted', label: 'Matte' },
          { value: 'wood', label: 'Stoneware' },
        ],
      },
      {
        kind: 'enum',
        key: 'contents',
        label: 'Contents',
        default: 'fruit',
        options: [
          { value: 'fruit', label: 'Fruit' },
          { value: 'empty', label: 'Empty' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.35 },
    ],
  },
  'magazine-stack': {
    kind: 'parametric',
    id: 'magazine-stack',
    name: 'Magazine stack',
    keywords: ['magazines', 'coffee table books', 'periodicals', 'reading material'],
    category: 'decor',
    primitive: 'MagazineStack',
    defaultFootprint: { w: 0.3, d: 0.24, h: 0.06 },
    verticalSpan: { base: 0.42, top: 0.48 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.2,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      { kind: 'color', key: 'color1', label: 'Cover 1', default: '#c03030' },
      { kind: 'color', key: 'color2', label: 'Cover 2', default: '#2c5a8a' },
      { kind: 'color', key: 'color3', label: 'Cover 3', default: '#c8a840' },
    ],
  },
  'small-sculpture': {
    kind: 'parametric',
    id: 'small-sculpture',
    name: 'Sculpture',
    keywords: [
      'sculpture',
      'abstract',
      'ornament',
      'objet dart',
      'accent piece',
      'decorative object',
    ],
    category: 'decor',
    primitive: 'SmallSculpture',
    defaultFootprint: { w: 0.14, d: 0.14, h: 0.18 },
    verticalSpan: { base: 0.42, top: 0.6 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.2,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#c0a87a' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'twist',
        options: [
          { value: 'twist', label: 'Twisted stack' },
          { value: 'arch', label: 'Arch' },
          { value: 'sphere', label: 'Orb' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'gloss',
        options: [
          { value: 'gloss', label: 'Polished' },
          { value: 'painted', label: 'Matte' },
          { value: 'wood', label: 'Natural' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.5 },
    ],
  },
  'desk-plant': {
    kind: 'parametric',
    id: 'desk-plant',
    name: 'Desk plant',
    keywords: [
      'succulent',
      'desktop plant',
      'small plant',
      'mini plant',
      'shelf plant',
      'trailing plant',
    ],
    category: 'decor',
    primitive: 'DeskPlant',
    defaultFootprint: { w: 0.16, d: 0.16, h: 0.14 },
    verticalSpan: { base: 0.72, top: 0.86 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.4,
        step: 0.02,
        default: 0.72,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'type',
        label: 'Type',
        default: 'succulent',
        options: [
          { value: 'succulent', label: 'Succulent' },
          { value: 'trailing', label: 'Trailing' },
        ],
      },
      { kind: 'color', key: 'potColor', label: 'Pot', default: '#c4956a' },
      { kind: 'color', key: 'leafColor', label: 'Foliage', default: '#4a8a44' },
      {
        kind: 'enum',
        key: 'potFinish',
        label: 'Pot finish',
        default: 'painted',
        options: [
          { value: 'painted', label: 'Matte' },
          { value: 'gloss', label: 'Glazed' },
          { value: 'wood', label: 'Terracotta' },
        ],
      },
    ],
  },
  'photo-frame-cluster': {
    kind: 'parametric',
    id: 'photo-frame-cluster',
    name: 'Photo frames',
    keywords: [
      'picture frames',
      'photo frames',
      'tabletop frames',
      'family photos',
      'portrait frames',
    ],
    category: 'decor',
    primitive: 'PhotoFrameCluster',
    defaultFootprint: { w: 0.28, d: 0.12, h: 0.18 },
    verticalSpan: { base: 0.42, top: 0.6 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.2,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      { kind: 'color', key: 'frameColor', label: 'Frames', default: '#2c2420' },
      { kind: 'color', key: 'matColor', label: 'Photo mat', default: '#f0ead8' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Frame finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'gloss', label: 'Metal/Gloss' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.1 },
    ],
  },
  'trailing-plant': {
    kind: 'parametric',
    id: 'trailing-plant',
    name: 'Trailing plant',
    keywords: [
      'trailing plant',
      'pothos',
      'cascading plant',
      'ivy',
      'vine',
      'hanging vine',
      'devil ivy',
      'shelf plant',
    ],
    category: 'decor',
    primitive: 'TrailingPlant',
    // Footprint spans the cascade so the vines reading over the edge are honest.
    defaultFootprint: { w: 0.28, d: 0.28, h: 0.32 },
    // Pot crown reaches ~0.18 above the surface; vines drape ~0.3 m below it, so
    // the rendered span runs from below the surface up past the crown.
    verticalSpan: { base: 0.12, top: 0.62 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.4,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      { kind: 'color', key: 'potColor', label: 'Pot', default: '#cdbb9a' },
      { kind: 'color', key: 'leafColor', label: 'Foliage', default: '#4a7a44' },
      {
        kind: 'enum',
        key: 'fullness',
        label: 'Fullness',
        default: 'full',
        options: [
          { value: 'full', label: 'Full' },
          { value: 'sparse', label: 'Sparse' },
        ],
      },
      {
        kind: 'enum',
        key: 'potFinish',
        label: 'Pot finish',
        default: 'painted',
        options: [
          { value: 'painted', label: 'Matte' },
          { value: 'gloss', label: 'Glazed' },
          { value: 'wood', label: 'Terracotta' },
        ],
      },
    ],
  },
  'decor-tray': {
    kind: 'parametric',
    id: 'decor-tray',
    name: 'Decor tray',
    keywords: [
      'tray',
      'styling tray',
      'vignette',
      'tabletop tray',
      'serving tray',
      'coffee table styling',
      'candle tray',
    ],
    category: 'decor',
    primitive: 'DecorTray',
    // Footprint covers the tray plus the objects standing inside it.
    defaultFootprint: { w: 0.34, d: 0.22, h: 0.13 },
    // Base sits ~0.018 above the surface; the tallest object (candle/bowl)
    // reaches ~0.13, so the span runs from the surface up past the vignette.
    verticalSpan: { base: 0.42, top: 0.55 },
    noClip: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.4,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'style',
        label: 'Arrangement',
        default: 'mixed',
        options: [
          { value: 'mixed', label: 'Mixed (candle + bowl + books)' },
          { value: 'candles', label: 'Candles' },
          { value: 'minimal', label: 'Minimal' },
        ],
      },
      {
        kind: 'enum',
        key: 'fullness',
        label: 'Fullness',
        default: 'full',
        options: [
          { value: 'full', label: 'Full' },
          { value: 'sparse', label: 'Sparse' },
        ],
      },
      { kind: 'color', key: 'trayColor', label: 'Tray', default: '#b8987a' },
      { kind: 'color', key: 'accentColor', label: 'Objects', default: '#7a8a7c' },
      {
        kind: 'enum',
        key: 'trayFinish',
        label: 'Tray finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Matte' },
          { value: 'gloss', label: 'Lacquer' },
        ],
      },
    ],
  },
} satisfies Record<string, FurnitureDef>
