import type { FurnitureDef } from '../types'

/** kids furniture definitions. Part of the built-in catalog (see ../builtinCatalog.ts). */
export const KIDS_DEFS = {
  'changing-table': {
    kind: 'parametric',
    id: 'changing-table',
    name: 'Changing table',
    category: 'kids',
    keywords: ['nursery', 'baby', 'changer', 'storage', 'dresser'],
    primitive: 'ChangingTable',
    defaultFootprint: { w: 0.95, d: 0.55, h: 1.1 },
    footprintParams: { w: 'width', d: 'depth' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.8,
        max: 1.2,
        step: 0.05,
        default: 0.95,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.45,
        max: 0.65,
        step: 0.02,
        default: 0.55,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Body', default: '#e6ddca' },
      { kind: 'color', key: 'padColor', label: 'Mat', default: '#cfe0d6' },
      {
        kind: 'enum',
        key: 'base',
        label: 'Base',
        default: 'drawers',
        options: [
          { value: 'drawers', label: 'Drawers' },
          { value: 'shelves', label: 'Open shelves' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'painted',
        options: [
          { value: 'painted', label: 'Painted' },
          { value: 'wood', label: 'Wood' },
          { value: 'gloss', label: 'Gloss' },
          { value: 'concrete', label: 'Concrete' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'high-chair': {
    kind: 'parametric',
    id: 'high-chair',
    name: 'High chair',
    category: 'kids',
    keywords: ['baby', 'feeding chair', 'nursery', 'seating'],
    primitive: 'HighChair',
    defaultFootprint: { w: 0.46, d: 0.5, h: 0.9 },
    paramSchema: [
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#caa46a' },
      { kind: 'color', key: 'seatColor', label: 'Seat / tray', default: '#e7e2d6' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood frame' },
          { value: 'plastic', label: 'Moulded plastic' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.1 },
    ],
  },
  crib: {
    kind: 'parametric',
    id: 'crib',
    name: 'Baby crib',
    category: 'kids',
    keywords: [
      'cot',
      'bassinet',
      'baby bed',
      'nursery',
      'bed',
      'convertible',
      'cot-bed',
      'toddler',
    ],
    primitive: 'Crib',
    defaultFootprint: { w: 1.32, d: 0.72, h: 0.96 },
    footprintParams: { w: 'width', d: 'depth' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Length',
        min: 1.1,
        max: 1.4,
        step: 0.02,
        default: 1.32,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Width',
        min: 0.6,
        max: 0.8,
        step: 0.02,
        default: 0.72,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Frame', default: '#cdb89c' },
      { kind: 'color', key: 'mattressColor', label: 'Mattress', default: '#eef1f4' },
      {
        kind: 'enum',
        key: 'mattressLevel',
        label: 'Base height',
        default: 'low',
        options: [
          { value: 'low', label: 'Low (sitting)' },
          { value: 'high', label: 'High (newborn)' },
        ],
      },
      {
        kind: 'enum',
        key: 'endStyle',
        label: 'Ends',
        default: 'slat',
        options: [
          { value: 'slat', label: 'Slatted' },
          { value: 'solid', label: 'Solid panel' },
        ],
      },
      {
        kind: 'enum',
        key: 'convert',
        label: 'Mode',
        default: 'crib',
        options: [
          { value: 'crib', label: 'Crib' },
          { value: 'toddler', label: 'Toddler bed' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'toddler-bed': {
    kind: 'parametric',
    id: 'toddler-bed',
    name: 'Toddler bed',
    category: 'kids',
    keywords: ['kids bed', 'junior bed', 'child bed', 'nursery', 'bed', 'cot'],
    primitive: 'ToddlerBed',
    defaultFootprint: { w: 0.78, d: 1.45, h: 0.5 },
    paramSchema: [
      { kind: 'color', key: 'color', label: 'Frame', default: '#c8b48f' },
      { kind: 'color', key: 'bedding', label: 'Bedding', default: '#e7e0d2' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'painted',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
    ],
  },
  'toy-storage': {
    kind: 'parametric',
    id: 'toy-storage',
    name: 'Toy storage organiser',
    category: 'kids',
    primitive: 'ToyStorage',
    // Default 3×2 kid-height cubbies (cube 0.28 + 0.025 panels).
    defaultFootprint: { w: 0.94, d: 0.3, h: 0.64 },
    paramSchema: [
      { kind: 'integer', key: 'cols', label: 'Columns', min: 2, max: 4, default: 3 },
      { kind: 'integer', key: 'rows', label: 'Rows', min: 1, max: 3, default: 2 },
      { kind: 'color', key: 'color', label: 'Frame colour', default: '#d8c6a8' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'loft-bed': {
    kind: 'parametric',
    id: 'loft-bed',
    name: 'Loft bed',
    category: 'kids',
    keywords: ['cabin bed', 'high sleeper', 'mid sleeper', 'bunk', 'space saver', 'raised bed'],
    primitive: 'LoftBed',
    // Fixed single-mattress platform (~1.0 × 2.0 m) at ~1.75 m; the under-bed
    // fit-out sits within this footprint, so no per-mode footprint change.
    defaultFootprint: { w: 1.0, d: 2.0, h: 2.1 },
    paramSchema: [
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#c2a06a' },
      { kind: 'color', key: 'bedding', label: 'Bedding', default: '#cdd7de' },
      {
        // Under-bed fit-out. `under` is not a first-structural-enum key; the
        // desk/wardrobe fit-outs are asserted via the harness EXTRA_MODES map
        // (the `open` default is the base swept case).
        kind: 'enum',
        key: 'under',
        label: 'Under-bed',
        default: 'open',
        options: [
          { value: 'open', label: 'Open space' },
          { value: 'desk', label: 'Built-in desk' },
          { value: 'wardrobe', label: 'Wardrobe' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'painted',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
} satisfies Record<string, FurnitureDef>
