import type { FurnitureDef } from '../types'

/** kitchen furniture definitions. Part of the built-in catalog (see ../builtinCatalog.ts). */
export const KITCHEN_DEFS = {
  'wall-cabinet': {
    kind: 'parametric',
    id: 'wall-cabinet',
    name: 'Wall cabinets',
    keywords: ['upper cabinet', 'kitchen cabinet', 'cupboard'],
    category: 'kitchen',
    primitive: 'WallCabinet',
    defaultFootprint: { w: 2.4, d: 0.35, h: 0.7 },
    footprintParams: { w: 'length' },
    mounted: true,
    verticalSpan: { base: 1.4, top: 2.2 },
    paramSchema: [
      {
        kind: 'number',
        key: 'length',
        label: 'Length',
        min: 0.6,
        max: 4.0,
        step: 0.1,
        default: 2.4,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Underside',
        min: 1.2,
        max: 1.7,
        step: 0.05,
        default: 1.45,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#e3dfd6' },
      {
        kind: 'enum',
        key: 'frontStyle',
        label: 'Fronts',
        default: 'slab',
        options: [
          { value: 'slab', label: 'Slab doors' },
          { value: 'shaker', label: 'Shaker doors' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'painted',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'range-hood': {
    kind: 'parametric',
    id: 'range-hood',
    name: 'Range hood',
    keywords: ['extractor', 'cooker hood', 'exhaust hood', 'vent hood'],
    category: 'kitchen',
    primitive: 'RangeHood',
    defaultFootprint: { w: 0.7, d: 0.45, h: 0.9 },
    mounted: true,
    verticalSpan: { base: 1.4, top: 2.3 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.6,
        max: 0.9,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Underside',
        min: 1.3,
        max: 1.6,
        step: 0.05,
        default: 1.45,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#c4c8cc' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'steel',
        options: [
          { value: 'matte', label: 'Matte' },
          { value: 'steel', label: 'Stainless steel' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
    ],
  },
  stove: {
    kind: 'parametric',
    id: 'stove',
    name: 'Cooker / stove',
    keywords: ['oven', 'hob', 'cooktop', 'range', 'gas stove', 'induction'],
    category: 'kitchen',
    primitive: 'Stove',
    defaultFootprint: { w: 0.6, d: 0.6, h: 0.92 },
    paramSchema: [
      { kind: 'color', key: 'color', label: 'Colour', default: '#cfd2d6' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'steel',
        options: [
          { value: 'matte', label: 'Matte' },
          { value: 'steel', label: 'Stainless steel' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
    ],
  },
  'kitchen-island': {
    kind: 'parametric',
    id: 'kitchen-island',
    name: 'Kitchen island',
    category: 'kitchen',
    keywords: ['island', 'breakfast bar', 'peninsula'],
    primitive: 'KitchenIsland',
    defaultFootprint: { w: 1.6, d: 0.95, h: 0.9 },
    footprintParams: { w: 'length', d: 'depth' },
    paramSchema: [
      {
        kind: 'number',
        key: 'length',
        label: 'Length',
        min: 1.0,
        max: 2.4,
        step: 0.1,
        default: 1.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.8,
        max: 1.1,
        step: 0.05,
        default: 0.95,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Cabinet', default: '#3a4754' },
      { kind: 'color', key: 'worktopColor', label: 'Worktop', default: '#2c2f34' },
      {
        kind: 'enum',
        key: 'worktopFinish',
        label: 'Worktop material',
        default: 'marble',
        options: [
          { value: 'marble', label: 'Stone / marble' },
          { value: 'sintered', label: 'Sintered stone' },
          { value: 'concrete', label: 'Concrete' },
          { value: 'wood', label: 'Butcher block' },
          { value: 'gloss', label: 'Gloss / solid' },
        ],
      },
      {
        kind: 'enum',
        key: 'top',
        label: 'Top',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'sink', label: 'With sink' },
          { value: 'hob', label: 'With hob' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'painted',
        options: [
          { value: 'painted', label: 'Painted' },
          { value: 'wood', label: 'Wood' },
          { value: 'gloss', label: 'Gloss' },
          { value: 'concrete', label: 'Concrete' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0.1 },
    ],
  },
  'kitchen-counter-l': {
    kind: 'parametric',
    id: 'kitchen-counter-l',
    name: 'Kitchen counter',
    category: 'kitchen',
    primitive: 'KitchenCounter',
    defaultFootprint: { w: 2.4, d: 0.6, h: 0.9 },
    footprintParams: { w: 'length' },
    paramSchema: [
      {
        kind: 'number',
        key: 'length',
        label: 'Length',
        min: 1.2,
        max: 4.0,
        step: 0.1,
        default: 2.4,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'hasSink',
        label: 'Sink',
        default: 'no',
        options: [
          { value: 'no', label: 'None' },
          { value: 'yes', label: 'Sink' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Cabinet', default: '#e3dfd6' },
      { kind: 'color', key: 'worktopColor', label: 'Worktop', default: '#34373d' },
      {
        kind: 'enum',
        key: 'worktopFinish',
        label: 'Worktop material',
        default: 'solid',
        options: [
          { value: 'solid', label: 'Solid (laminate)' },
          { value: 'marble', label: 'Stone / marble' },
          { value: 'sintered', label: 'Sintered stone' },
          { value: 'concrete', label: 'Concrete' },
          { value: 'wood', label: 'Butcher block' },
        ],
      },
      {
        kind: 'enum',
        key: 'frontStyle',
        label: 'Fronts',
        default: 'slab',
        options: [
          { value: 'slab', label: 'Slab doors' },
          { value: 'shaker', label: 'Shaker doors' },
          { value: 'drawers', label: 'Drawers' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'painted',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
} satisfies Record<string, FurnitureDef>
