import type { FurnitureDef } from '../types'

/** lighting furniture definitions. Part of the built-in catalog (see ../builtinCatalog.ts). */
export const LIGHTING_DEFS = {
  // ── Lighting ────────────────────────────────────────────────────────────
  'cove-light': {
    kind: 'parametric',
    id: 'cove-light',
    name: 'Cove light (LED)',
    category: 'lighting',
    primitive: 'CoveLight',
    defaultFootprint: { w: 2.0, d: 0.16, h: 0.12 },
    footprintParams: { w: 'length' },
    mounted: true,
    verticalSpan: { base: 2.2, top: 2.45 },
    paramSchema: [
      {
        kind: 'number',
        key: 'length',
        label: 'Length',
        min: 0.6,
        max: 4.0,
        step: 0.1,
        default: 2.0,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 2.0,
        max: 2.55,
        step: 0.05,
        default: 2.3,
        unit: 'm',
      },
      { kind: 'color', key: 'ledColor', label: 'LED', default: '#ffcf94' },
      {
        kind: 'enum',
        key: 'lightColor',
        label: 'Bulb',
        default: '#ffd9a0',
        options: [
          { value: '#ffd9a0', label: 'Warm' },
          { value: '#fff1da', label: 'Neutral' },
          { value: '#e6efff', label: 'Cool' },
        ],
      },
      { kind: 'color', key: 'boxColor', label: 'Box', default: '#f1efea' },
    ],
  },
  'wall-sconce': {
    kind: 'parametric',
    id: 'wall-sconce',
    name: 'Wall sconce',
    keywords: ['sconce', 'wall light'],
    category: 'lighting',
    primitive: 'WallSconce',
    defaultFootprint: { w: 0.14, d: 0.18, h: 0.2 },
    mounted: true,
    verticalSpan: { base: 1.55, top: 1.85 },
    paramSchema: [
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 1.2,
        max: 2.2,
        step: 0.05,
        default: 1.7,
        unit: 'm',
      },
      { kind: 'color', key: 'shadeColor', label: 'Diffuser', default: '#f3e7c6' },
      {
        kind: 'enum',
        key: 'lightColor',
        label: 'Bulb',
        default: '#ffd9a0',
        options: [
          { value: '#ffd9a0', label: 'Warm' },
          { value: '#fff1da', label: 'Neutral' },
          { value: '#e6efff', label: 'Cool' },
        ],
      },
      { kind: 'color', key: 'metalColor', label: 'Fitting', default: '#2c2f33' },
    ],
  },
  'table-lamp': {
    kind: 'parametric',
    id: 'table-lamp',
    name: 'Table lamp',
    keywords: ['lamp', 'desk lamp'],
    category: 'lighting',
    primitive: 'TableLamp',
    defaultFootprint: { w: 0.3, d: 0.3, h: 0.44 },
    verticalSpan: { base: 0.52, top: 0.98 },
    paramSchema: [
      {
        kind: 'number',
        key: 'surfaceHeight',
        label: 'Sits at',
        min: 0,
        max: 1.0,
        step: 0.02,
        default: 0.52,
        unit: 'm',
      },
      { kind: 'color', key: 'shadeColor', label: 'Shade', default: '#f0e4c4' },
      {
        kind: 'enum',
        key: 'lightColor',
        label: 'Bulb',
        default: '#ffd9a0',
        options: [
          { value: '#ffd9a0', label: 'Warm' },
          { value: '#fff1da', label: 'Neutral' },
          { value: '#e6efff', label: 'Cool' },
        ],
      },
      { kind: 'color', key: 'baseColor', label: 'Base', default: '#33363b' },
      {
        kind: 'enum',
        key: 'shade',
        label: 'Shade shape',
        default: 'empire',
        options: [
          { value: 'empire', label: 'Empire' },
          { value: 'drum', label: 'Drum' },
          { value: 'cone', label: 'Cone' },
        ],
      },
    ],
  },
  'floor-lamp': {
    kind: 'parametric',
    id: 'floor-lamp',
    name: 'Floor lamp',
    keywords: ['standing lamp', 'lamp'],
    category: 'lighting',
    primitive: 'FloorLamp',
    defaultFootprint: { w: 0.42, d: 0.42, h: 1.8 },
    paramSchema: [
      { kind: 'color', key: 'shadeColor', label: 'Shade', default: '#f3e6c8' },
      {
        kind: 'enum',
        key: 'lightColor',
        label: 'Bulb',
        default: '#ffd9a0',
        options: [
          { value: '#ffd9a0', label: 'Warm' },
          { value: '#fff1da', label: 'Neutral' },
          { value: '#e6efff', label: 'Cool' },
        ],
      },
      { kind: 'color', key: 'poleColor', label: 'Pole / legs', default: '#2b2b2b' },
      {
        kind: 'enum',
        key: 'base',
        label: 'Base',
        default: 'disc',
        options: [
          { value: 'disc', label: 'Disc + pole' },
          { value: 'tripod', label: 'Tripod' },
          { value: 'arc', label: 'Arc (over-sofa)' },
        ],
      },
      {
        kind: 'enum',
        key: 'shade',
        label: 'Shade shape',
        default: 'empire',
        options: [
          { value: 'empire', label: 'Empire' },
          { value: 'drum', label: 'Drum' },
          { value: 'cone', label: 'Cone' },
        ],
      },
    ],
  },
  'ceiling-light': {
    kind: 'parametric',
    id: 'ceiling-light',
    name: 'Ceiling light',
    keywords: ['pendant', 'pendant light', 'light fixture'],
    category: 'lighting',
    primitive: 'CeilingLight',
    defaultFootprint: { w: 0.45, d: 0.45, h: 0.5 },
    mounted: true,
    verticalSpan: { base: 2.0, top: 2.7 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'pendant',
        options: [
          { value: 'pendant', label: 'Pendant' },
          { value: 'linear', label: 'Linear bar' },
          { value: 'flush', label: 'Flush mount' },
        ],
      },
      {
        kind: 'enum',
        key: 'shade',
        label: 'Shade shape',
        default: 'dome',
        options: [
          { value: 'dome', label: 'Dome' },
          { value: 'globe', label: 'Globe' },
          { value: 'cone', label: 'Cone' },
          { value: 'drum', label: 'Drum' },
        ],
      },
      { kind: 'color', key: 'shadeColor', label: 'Shade', default: '#f2ead6' },
      {
        kind: 'enum',
        key: 'lightColor',
        label: 'Bulb',
        default: '#ffd9a0',
        options: [
          { value: '#ffd9a0', label: 'Warm' },
          { value: '#fff1da', label: 'Neutral' },
          { value: '#e6efff', label: 'Cool' },
        ],
      },
    ],
  },
} satisfies Record<string, FurnitureDef>
