import type { FurnitureDef } from '../types'

/**
 * Pet fittings & furniture (Pet program, Stage P1). Part of the built-in catalog
 * (see ../builtinCatalog.ts), gated behind the `petFittings` feature flag.
 *
 * P1 ships the foundations + the Singapore-compliance fittings: the pet bed
 * (moved here from `decor`, id unchanged), the Cat-Management-Framework window /
 * balcony safety mesh screen (`windowBound`), the doorway pet gate + pet-door
 * insert (`doorBound`), and a freestanding playpen.
 *
 * P2 ships the cat set: a parametric cat tree (sisal posts + plush platforms,
 * staggered tiers, optional house cube + top perch), mounted cat wall shelves /
 * steps / bridge (`mounted` + `mountHeight`), scratching posts, litter boxes +
 * a concealment cabinet, a sill-level window perch (`windowBound`), and a fabric
 * tunnel. All procedural, real-metre, structurally sound. The modular cat tree
 * also ships as a slot-configurator product (`configurator/products.ts`).
 */
export const PETS_DEFS = {
  'pet-bed': {
    kind: 'parametric',
    id: 'pet-bed',
    name: 'Pet bed',
    keywords: ['dog bed', 'cat bed', 'pet', 'basket', 'dog', 'cat'],
    category: 'pets',
    primitive: 'PetBed',
    defaultFootprint: { w: 0.7, d: 0.7, h: 0.22 },
    footprintParams: { w: 'size', d: 'size' },
    paramSchema: [
      {
        kind: 'number',
        key: 'size',
        label: 'Size',
        min: 0.45,
        max: 1.1,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'round',
        options: [
          { value: 'round', label: 'Round basket' },
          { value: 'rect', label: 'Rectangular mat' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Bolster', default: '#9b6f52' },
      { kind: 'color', key: 'cushion', label: 'Cushion', default: '#d8c9b0' },
    ],
  },
  'window-mesh-screen': {
    kind: 'parametric',
    id: 'window-mesh-screen',
    name: 'Window mesh screen',
    keywords: [
      'cat',
      'mesh',
      'screen',
      'safety',
      'CMF',
      'compliance',
      'window',
      'balcony',
      'net',
      'grille',
    ],
    category: 'pets',
    primitive: 'WindowMeshScreen',
    defaultFootprint: { w: 1.2, d: 0.08, h: 2.1 },
    // Sits flat on a window opening — never blocks floor placement.
    noClip: true,
    // Window-bound: statically placed on a window (no move/rotate/flip);
    // placement snaps + sizes it to the opening (width + sill/head).
    windowBound: true,
    paramSchema: [
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#3a3d42' },
      {
        kind: 'enum',
        key: 'frameFinish',
        label: 'Frame finish',
        default: 'satin',
        options: [
          { value: 'satin', label: 'Satin' },
          { value: 'black-steel', label: 'Black steel' },
        ],
      },
      {
        kind: 'enum',
        key: 'density',
        label: 'Mesh density',
        default: 'fine',
        options: [
          { value: 'fine', label: 'Fine (cat-safe)' },
          { value: 'standard', label: 'Standard' },
        ],
      },
      {
        kind: 'enum',
        key: 'frameStyle',
        label: 'Frame style',
        default: 'slim',
        options: [
          { value: 'slim', label: 'Slim' },
          { value: 'box', label: 'Box section' },
        ],
      },
      { kind: 'color', key: 'meshColor', label: 'Mesh', default: '#2b2d31' },
    ],
  },
  'pet-gate': {
    kind: 'parametric',
    id: 'pet-gate',
    name: 'Pet gate',
    keywords: ['dog', 'cat', 'gate', 'barrier', 'doorway', 'safety', 'stair gate'],
    category: 'pets',
    primitive: 'PetGate',
    defaultFootprint: { w: 0.85, d: 0.06, h: 0.75 },
    noClip: true,
    // Door-bound: statically placed spanning a doorway (no move/rotate/flip);
    // placement snaps + sizes it to the door opening.
    doorBound: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.6,
        max: 1.1,
        step: 0.05,
        default: 0.75,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'bars',
        options: [
          { value: 'bars', label: 'Bars' },
          { value: 'mesh', label: 'Mesh' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#6b6f76' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'satin',
        options: [
          { value: 'satin', label: 'Satin' },
          { value: 'black-steel', label: 'Black steel' },
        ],
      },
      {
        kind: 'enum',
        key: 'flap',
        label: 'Walk-through flap',
        default: 'no',
        options: [
          { value: 'no', label: 'None' },
          { value: 'yes', label: 'Flap section' },
        ],
      },
    ],
  },
  'pet-door-insert': {
    kind: 'parametric',
    id: 'pet-door-insert',
    name: 'Pet door insert',
    keywords: ['dog', 'cat', 'flap', 'pet door', 'doggie door', 'cat flap', 'doorway'],
    category: 'pets',
    primitive: 'PetDoorInsert',
    defaultFootprint: { w: 0.82, d: 0.06, h: 0.6 },
    noClip: true,
    doorBound: true,
    paramSchema: [
      {
        kind: 'enum',
        key: 'flapSize',
        label: 'Flap size',
        default: 'M',
        options: [
          { value: 'S', label: 'Small' },
          { value: 'M', label: 'Medium' },
        ],
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#c9c4bb' },
    ],
  },
  'pet-playpen': {
    kind: 'parametric',
    id: 'pet-playpen',
    name: 'Pet playpen',
    keywords: ['dog', 'cat', 'puppy', 'playpen', 'pen', 'enclosure', 'crate', 'fence'],
    category: 'pets',
    primitive: 'PetPlaypen',
    defaultFootprint: { w: 1.25, d: 1.25, h: 0.7 },
    // Clear floor in front so the pen has access space (IKEA design semantics).
    frontClearance: 0.5,
    paramSchema: [
      {
        kind: 'integer',
        key: 'panels',
        label: 'Panels',
        min: 4,
        max: 8,
        default: 6,
      },
      {
        kind: 'number',
        key: 'panelWidth',
        label: 'Panel width',
        min: 0.4,
        max: 0.9,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'panelHeight',
        label: 'Panel height',
        min: 0.45,
        max: 1.0,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Wire', default: '#5b6068' },
      {
        kind: 'enum',
        key: 'wireFinish',
        label: 'Finish',
        default: 'satin',
        options: [
          { value: 'satin', label: 'Satin' },
          { value: 'black-steel', label: 'Black steel' },
        ],
      },
    ],
  },
  // ---- Stage P2 — the cat set --------------------------------------------
  'cat-tree': {
    kind: 'parametric',
    id: 'cat-tree',
    name: 'Cat tree',
    keywords: ['cat', 'cat tree', 'condo', 'tower', 'climbing', 'scratching', 'perch', 'sisal'],
    category: 'pets',
    primitive: 'CatTree',
    defaultFootprint: { w: 0.5, d: 0.5, h: 1.4 },
    footprintParams: { w: 'baseWidth', d: 'baseWidth' },
    verticalSpan: { base: 0, top: 1.8 },
    paramSchema: [
      { kind: 'integer', key: 'tiers', label: 'Tiers', min: 2, max: 5, default: 3 },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.9,
        max: 1.8,
        step: 0.05,
        default: 1.4,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'baseWidth',
        label: 'Base width',
        min: 0.4,
        max: 0.6,
        step: 0.05,
        default: 0.5,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'postStyle',
        label: 'Posts',
        default: 'sisal',
        options: [
          { value: 'sisal', label: 'Sisal rope' },
          { value: 'ribbed', label: 'Ribbed' },
        ],
      },
      {
        kind: 'enum',
        key: 'house',
        label: 'House cube',
        default: 'yes',
        options: [
          { value: 'yes', label: 'Include' },
          { value: 'no', label: 'None' },
        ],
      },
      {
        kind: 'enum',
        key: 'topPerch',
        label: 'Top perch',
        default: 'yes',
        options: [
          { value: 'yes', label: 'Include' },
          { value: 'no', label: 'None' },
        ],
      },
      { kind: 'color', key: 'plushColor', label: 'Plush', default: '#c8bda8' },
      { kind: 'color', key: 'postColor', label: 'Rope', default: '#c9a875' },
    ],
  },
  'cat-wall-shelf': {
    kind: 'parametric',
    id: 'cat-wall-shelf',
    name: 'Cat wall shelf',
    keywords: ['cat', 'wall shelf', 'ledge', 'climbing', 'perch', 'mounted'],
    category: 'pets',
    primitive: 'CatWallShelf',
    defaultFootprint: { w: 0.5, d: 0.28, h: 0.1 },
    footprintParams: { w: 'width', d: 'depth' },
    mounted: true,
    verticalSpan: { base: 1.2, top: 1.42 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.35,
        max: 0.9,
        step: 0.05,
        default: 0.5,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.25,
        max: 0.3,
        step: 0.01,
        default: 0.28,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 0.6,
        max: 2.2,
        step: 0.05,
        default: 1.3,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#8a6b48' },
      { kind: 'color', key: 'plushColor', label: 'Grip pad', default: '#c8bda8' },
    ],
  },
  'cat-wall-steps': {
    kind: 'parametric',
    id: 'cat-wall-steps',
    name: 'Cat wall steps',
    keywords: ['cat', 'steps', 'stairs', 'climbing', 'wall', 'mounted', 'diagonal'],
    category: 'pets',
    primitive: 'CatWallSteps',
    defaultFootprint: { w: 1.5, d: 0.26, h: 1.0 },
    mounted: true,
    verticalSpan: { base: 0.85, top: 1.85 },
    paramSchema: [
      { kind: 'integer', key: 'count', label: 'Steps', min: 3, max: 5, default: 4 },
      {
        kind: 'number',
        key: 'rise',
        label: 'Rise',
        min: 0.18,
        max: 0.38,
        step: 0.02,
        default: 0.28,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'run',
        label: 'Run',
        min: 0.3,
        max: 0.55,
        step: 0.05,
        default: 0.4,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'stepWidth',
        label: 'Step width',
        min: 0.28,
        max: 0.45,
        step: 0.01,
        default: 0.34,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'First step',
        min: 0.4,
        max: 1.2,
        step: 0.05,
        default: 0.9,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#8a6b48' },
      { kind: 'color', key: 'plushColor', label: 'Grip pad', default: '#c8bda8' },
    ],
  },
  'cat-wall-bridge': {
    kind: 'parametric',
    id: 'cat-wall-bridge',
    name: 'Cat wall bridge',
    keywords: ['cat', 'bridge', 'catwalk', 'span', 'wall', 'mounted', 'slats'],
    category: 'pets',
    primitive: 'CatWallBridge',
    defaultFootprint: { w: 1.2, d: 0.26, h: 0.1 },
    footprintParams: { w: 'span', d: 'depth' },
    mounted: true,
    verticalSpan: { base: 1.5, top: 1.72 },
    paramSchema: [
      {
        kind: 'number',
        key: 'span',
        label: 'Span',
        min: 0.8,
        max: 2.0,
        step: 0.1,
        default: 1.2,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.22,
        max: 0.3,
        step: 0.02,
        default: 0.26,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 0.8,
        max: 2.2,
        step: 0.05,
        default: 1.6,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#8a6b48' },
      { kind: 'color', key: 'plushColor', label: 'Treads', default: '#c8bda8' },
    ],
  },
  'scratching-post': {
    kind: 'parametric',
    id: 'scratching-post',
    name: 'Scratching post',
    keywords: ['cat', 'scratcher', 'scratching post', 'sisal', 'pad'],
    category: 'pets',
    primitive: 'ScratchingPost',
    defaultFootprint: { w: 0.44, d: 0.44, h: 0.74 },
    verticalSpan: { base: 0, top: 0.82 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'vertical',
        options: [
          { value: 'vertical', label: 'Vertical post' },
          { value: 'angled', label: 'Angled board' },
          { value: 'pad', label: 'Floor pad' },
        ],
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.4,
        max: 0.9,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      { kind: 'color', key: 'sisalColor', label: 'Sisal', default: '#c9a875' },
      { kind: 'color', key: 'baseColor', label: 'Base', default: '#c8bda8' },
    ],
  },
  'litter-box': {
    kind: 'parametric',
    id: 'litter-box',
    name: 'Litter box',
    keywords: ['cat', 'litter', 'litter box', 'tray', 'toilet', 'covered'],
    category: 'pets',
    primitive: 'LitterBox',
    defaultFootprint: { w: 0.56, d: 0.46, h: 0.41 },
    // Clear floor in front so the entry is reachable (covered/top-entry access).
    frontClearance: 0.5,
    paramSchema: [
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'covered',
        options: [
          { value: 'open', label: 'Open tray' },
          { value: 'covered', label: 'Covered hood' },
          { value: 'top-entry', label: 'Top entry' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#5a6b74' },
    ],
  },
  'litter-cabinet': {
    kind: 'parametric',
    id: 'litter-cabinet',
    name: 'Litter cabinet',
    keywords: ['cat', 'litter', 'cabinet', 'enclosure', 'concealment', 'bench', 'furniture'],
    category: 'pets',
    primitive: 'LitterCabinet',
    defaultFootprint: { w: 0.72, d: 0.52, h: 0.5 },
    footprintParams: { w: 'width', d: 'depth' },
    frontClearance: 0.4,
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.65,
        max: 1.0,
        step: 0.05,
        default: 0.72,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.5,
        max: 0.65,
        step: 0.05,
        default: 0.52,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.45,
        max: 0.6,
        step: 0.05,
        default: 0.5,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'entrySide',
        label: 'Entry side',
        default: 'left',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'right', label: 'Right' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#9d7c54' },
    ],
  },
  'cat-window-perch': {
    kind: 'parametric',
    id: 'cat-window-perch',
    name: 'Cat window perch',
    keywords: ['cat', 'window', 'perch', 'sill', 'lounger', 'sunbathe'],
    category: 'pets',
    primitive: 'CatWindowPerch',
    defaultFootprint: { w: 0.7, d: 0.35, h: 0.35 },
    // Sits at the sill of a window; never blocks floor placement.
    noClip: true,
    // Window-bound: snaps to the nearest window and sits at sill height.
    windowBound: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.28,
        max: 0.42,
        step: 0.02,
        default: 0.32,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#8a6b48' },
      { kind: 'color', key: 'plushColor', label: 'Cushion', default: '#c8bda8' },
    ],
  },
  'cat-tunnel': {
    kind: 'parametric',
    id: 'cat-tunnel',
    name: 'Cat tunnel',
    keywords: ['cat', 'tunnel', 'tube', 'play', 'hideaway'],
    category: 'pets',
    primitive: 'CatTunnel',
    defaultFootprint: { w: 1.0, d: 0.3, h: 0.3 },
    footprintParams: { w: 'length', d: 'diameter' },
    verticalSpan: { base: 0, top: 0.32 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'straight',
        options: [
          { value: 'straight', label: 'Straight' },
          { value: 's-curve', label: 'S-curve' },
        ],
      },
      {
        kind: 'number',
        key: 'length',
        label: 'Length',
        min: 0.7,
        max: 1.6,
        step: 0.1,
        default: 1.0,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'diameter',
        label: 'Diameter',
        min: 0.24,
        max: 0.36,
        step: 0.02,
        default: 0.3,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Fabric', default: '#7f8a94' },
    ],
  },
} satisfies Record<string, FurnitureDef>
