import type { FurnitureDef } from '../types'

/**
 * Pet fittings & furniture (Pet program). Part of the built-in catalog
 * (see ../builtinCatalog.ts), gated behind the `petFittings` feature flag.
 *
 * Ordering (Stage P5 — catalog tab reads top-to-bottom in this order):
 *   1. Compliance / safety fittings first (the SG-differentiating items):
 *      window/balcony mesh screen, doorway pet gate, pet-door insert, playpen.
 *   2. Per-pet-type clusters: dog set, cat set, birds, small pets, fish.
 * The built-in catalog preserves this object's key order, so the tab grouping
 * IS this array order (see defs/pets.test.ts `catalog ordering`).
 *
 * Keyword curation (Stage P5): every def carries at least one pet-type keyword
 * (`dog` | `cat` | `bird` | `rabbit` | `guinea-pig` | `hamster` | `fish` |
 * `small-pet`) plus functional keywords (litter / mesh / gate / …) so catalog
 * search surfaces the right items. Compliance fittings match EVERY pet type they
 * serve — the mesh screen is the Cat-Management-Framework requirement (`cat`) but
 * also prevents dog/bird falls, and the playpen contains dogs/cats/rabbits/small
 * pets — so a search for any of those pets surfaces the compliance item too.
 *
 * All procedural, real-metre, structurally sound; every def is
 * paramSchema-customizable. The modular cat tree also ships as a slot-
 * configurator product (`configurator/products.ts`).
 */
export const PETS_DEFS = {
  // ============================================================================
  // 1. Compliance / safety fittings (SG Cat-Management-Framework + room safety)
  // ============================================================================
  'window-mesh-screen': {
    kind: 'parametric',
    id: 'window-mesh-screen',
    name: 'Window mesh screen',
    // Compliance fitting: the CMF cat-containment requirement (`cat`), but also
    // prevents dog / bird falls & fly-outs — match every pet type it serves.
    keywords: [
      'cat',
      'dog',
      'bird',
      'mesh',
      'screen',
      'safety',
      'CMF',
      'compliance',
      'window',
      'balcony',
      'net',
      'grille',
    ],
    category: 'pets',
    primitive: 'WindowMeshScreen',
    defaultFootprint: { w: 1.2, d: 0.08, h: 2.1 },
    // Sits flat on a window opening — never blocks floor placement.
    noClip: true,
    // Window-bound: statically placed on a window (no move/rotate/flip);
    // placement snaps + sizes it to the opening (width + sill/head).
    windowBound: true,
    paramSchema: [
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#3a3d42' },
      {
        kind: 'enum',
        key: 'frameFinish',
        label: 'Frame finish',
        default: 'satin',
        options: [
          { value: 'satin', label: 'Satin' },
          { value: 'black-steel', label: 'Black steel' },
        ],
      },
      {
        kind: 'enum',
        key: 'density',
        label: 'Mesh density',
        default: 'fine',
        options: [
          { value: 'fine', label: 'Fine (cat-safe)' },
          { value: 'standard', label: 'Standard' },
        ],
      },
      {
        kind: 'enum',
        key: 'frameStyle',
        label: 'Frame style',
        default: 'slim',
        options: [
          { value: 'slim', label: 'Slim' },
          { value: 'box', label: 'Box section' },
        ],
      },
      { kind: 'color', key: 'meshColor', label: 'Mesh', default: '#2b2d31' },
    ],
  },
  'pet-gate': {
    kind: 'parametric',
    id: 'pet-gate',
    name: 'Pet gate',
    keywords: ['dog', 'cat', 'gate', 'barrier', 'doorway', 'safety', 'stair gate', 'mesh'],
    category: 'pets',
    primitive: 'PetGate',
    defaultFootprint: { w: 0.85, d: 0.06, h: 0.75 },
    noClip: true,
    // Door-bound: statically placed spanning a doorway (no move/rotate/flip);
    // placement snaps + sizes it to the door opening.
    doorBound: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.6,
        max: 1.1,
        step: 0.05,
        default: 0.75,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'bars',
        options: [
          { value: 'bars', label: 'Bars' },
          { value: 'mesh', label: 'Mesh' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#6b6f76' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'satin',
        options: [
          { value: 'satin', label: 'Satin' },
          { value: 'black-steel', label: 'Black steel' },
        ],
      },
      {
        kind: 'enum',
        key: 'flap',
        label: 'Walk-through flap',
        default: 'no',
        options: [
          { value: 'no', label: 'None' },
          { value: 'yes', label: 'Flap section' },
        ],
      },
    ],
  },
  'pet-door-insert': {
    kind: 'parametric',
    id: 'pet-door-insert',
    name: 'Pet door insert',
    keywords: ['dog', 'cat', 'flap', 'pet door', 'doggie door', 'cat flap', 'doorway'],
    category: 'pets',
    primitive: 'PetDoorInsert',
    defaultFootprint: { w: 0.82, d: 0.06, h: 0.6 },
    noClip: true,
    doorBound: true,
    paramSchema: [
      {
        kind: 'enum',
        key: 'flapSize',
        label: 'Flap size',
        default: 'M',
        options: [
          { value: 'S', label: 'Small' },
          { value: 'M', label: 'Medium' },
        ],
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#c9c4bb' },
    ],
  },
  'pet-playpen': {
    kind: 'parametric',
    id: 'pet-playpen',
    name: 'Pet playpen',
    // Contains puppies/cats AND rabbits/small pets — a shared compliance fitting.
    keywords: [
      'dog',
      'cat',
      'rabbit',
      'small-pet',
      'puppy',
      'playpen',
      'pen',
      'enclosure',
      'crate',
      'fence',
    ],
    category: 'pets',
    primitive: 'PetPlaypen',
    defaultFootprint: { w: 1.25, d: 1.25, h: 0.7 },
    // Clear floor in front so the pen has access space (IKEA design semantics).
    frontClearance: 0.5,
    paramSchema: [
      {
        kind: 'integer',
        key: 'panels',
        label: 'Panels',
        min: 4,
        max: 8,
        default: 6,
      },
      {
        kind: 'number',
        key: 'panelWidth',
        label: 'Panel width',
        min: 0.4,
        max: 0.9,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'panelHeight',
        label: 'Panel height',
        min: 0.45,
        max: 1.0,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Wire', default: '#5b6068' },
      {
        kind: 'enum',
        key: 'wireFinish',
        label: 'Finish',
        default: 'satin',
        options: [
          { value: 'satin', label: 'Satin' },
          { value: 'black-steel', label: 'Black steel' },
        ],
      },
    ],
  },
  // ============================================================================
  // 2a. Dog set (+ the shared dog/cat freestanding pieces)
  // ============================================================================
  'pet-bed': {
    kind: 'parametric',
    id: 'pet-bed',
    name: 'Pet bed',
    keywords: ['dog bed', 'cat bed', 'pet', 'basket', 'dog', 'cat'],
    category: 'pets',
    primitive: 'PetBed',
    defaultFootprint: { w: 0.7, d: 0.7, h: 0.22 },
    footprintParams: { w: 'size', d: 'size' },
    paramSchema: [
      {
        kind: 'number',
        key: 'size',
        label: 'Size',
        min: 0.45,
        max: 1.1,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'round',
        options: [
          { value: 'round', label: 'Round basket' },
          { value: 'rect', label: 'Rectangular mat' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Bolster', default: '#9b6f52' },
      { kind: 'color', key: 'cushion', label: 'Cushion', default: '#d8c9b0' },
    ],
  },
  'dog-crate': {
    kind: 'parametric',
    id: 'dog-crate',
    name: 'Dog crate',
    keywords: ['dog', 'crate', 'kennel', 'cage', 'wire', 'furniture', 'side table'],
    category: 'pets',
    primitive: 'DogCrate',
    // The `size` enum drives the live dims in the primitive (XXS→M); enums can't
    // feed `footprintParams`, so the footprint is pinned to the LARGEST size (M)
    // — a conservative over-report for smaller crates, never an under-report
    // that would let an M crate clip a wall.
    defaultFootprint: { w: 0.61, d: 0.46, h: 0.51 },
    frontClearance: 0.4,
    paramSchema: [
      {
        kind: 'enum',
        key: 'size',
        label: 'Size',
        default: 'S',
        options: [
          { value: 'XXS', label: 'XXS (41 cm)' },
          { value: 'XS', label: 'XS (46 cm)' },
          { value: 'S', label: 'S (51 cm)' },
          { value: 'M', label: 'M (61 cm)' },
        ],
      },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'wire',
        options: [
          { value: 'wire', label: 'Wire crate' },
          { value: 'furniture', label: 'Wood-top (side table)' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Wire', default: '#6b6f76' },
      { kind: 'color', key: 'woodColor', label: 'Timber', default: '#9d7c54' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Wood finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
    ],
  },
  'dog-bed-orthopedic': {
    kind: 'parametric',
    id: 'dog-bed-orthopedic',
    name: 'Orthopedic dog bed',
    keywords: ['dog', 'bed', 'orthopedic', 'memory foam', 'bolster', 'mattress'],
    category: 'pets',
    primitive: 'DogBedOrthopedic',
    defaultFootprint: { w: 0.9, d: 0.65, h: 0.26 },
    footprintParams: { w: 'width', d: 'depth' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.6,
        max: 1.2,
        step: 0.05,
        default: 0.9,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.45,
        max: 0.9,
        step: 0.05,
        default: 0.65,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'bolster_style',
        label: 'Bolster',
        default: 'headrest',
        options: [
          { value: 'headrest', label: 'Back headrest' },
          { value: 'three-side', label: 'Three-side (U)' },
        ],
      },
      { kind: 'color', key: 'mattress', label: 'Mattress', default: '#c3c9cf' },
      { kind: 'color', key: 'bolster', label: 'Bolster', default: '#8a94a0' },
    ],
  },
  'pet-feeding-station': {
    kind: 'parametric',
    id: 'pet-feeding-station',
    name: 'Feeding station',
    keywords: ['dog', 'cat', 'feeder', 'bowls', 'raised', 'elevated', 'food', 'water'],
    category: 'pets',
    primitive: 'FeedingStation',
    defaultFootprint: { w: 0.56, d: 0.28, h: 0.2 },
    frontClearance: 0.4,
    paramSchema: [
      {
        kind: 'enum',
        key: 'bowls',
        label: 'Bowls',
        default: '2',
        options: [
          { value: '1', label: 'Single' },
          { value: '2', label: 'Double' },
        ],
      },
      {
        kind: 'number',
        key: 'standHeight',
        label: 'Stand height',
        min: 0.08,
        max: 0.25,
        step: 0.01,
        default: 0.14,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#9d7c54' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'bowlColor', label: 'Bowls (steel)', default: '#c9ccd0' },
    ],
  },
  'dog-ramp': {
    kind: 'parametric',
    id: 'dog-ramp',
    name: 'Dog ramp',
    keywords: ['dog', 'ramp', 'steps', 'stairs', 'sofa', 'bed', 'access', 'pet stairs'],
    category: 'pets',
    primitive: 'DogRamp',
    defaultFootprint: { w: 0.4, d: 0.95, h: 0.45 },
    footprintParams: { w: 'width', d: 'length' },
    paramSchema: [
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'ramp',
        options: [
          { value: 'ramp', label: 'Ramp' },
          { value: 'steps', label: 'Steps' },
        ],
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.4,
        max: 0.7,
        step: 0.05,
        default: 0.45,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'length',
        label: 'Run',
        min: 0.6,
        max: 1.4,
        step: 0.05,
        default: 0.95,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.3,
        max: 0.6,
        step: 0.05,
        default: 0.4,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'rails',
        label: 'Side rails',
        default: 'no',
        options: [
          { value: 'no', label: 'None' },
          { value: 'yes', label: 'Rails' },
        ],
      },
      { kind: 'color', key: 'tread', label: 'Tread (carpet)', default: '#7d746a' },
      { kind: 'color', key: 'frame', label: 'Frame', default: '#6b5947' },
    ],
  },
  'pet-cooling-mat': {
    kind: 'parametric',
    id: 'pet-cooling-mat',
    name: 'Cooling mat',
    keywords: ['dog', 'cat', 'cooling', 'gel', 'mat', 'pad', 'summer'],
    category: 'pets',
    primitive: 'CoolingMat',
    defaultFootprint: { w: 0.7, d: 0.5, h: 0.01 },
    // A thin flat covering — never blocks floor placement (like a rug).
    noClip: true,
    verticalSpan: { base: 0, top: 0.012 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'size',
        label: 'Size',
        default: 'M',
        options: [
          { value: 'S', label: 'Small (50 cm)' },
          { value: 'M', label: 'Medium (70 cm)' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Gel', default: '#7fb2c9' },
    ],
  },
  'pet-toy-bin': {
    kind: 'parametric',
    id: 'pet-toy-bin',
    name: 'Pet toy bin',
    keywords: ['dog', 'cat', 'toy', 'bin', 'basket', 'storage', 'woven'],
    category: 'pets',
    primitive: 'PetToyBin',
    defaultFootprint: { w: 0.4, d: 0.4, h: 0.32 },
    footprintParams: { w: 'width', d: 'depth' },
    paramSchema: [
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'round',
        options: [
          { value: 'round', label: 'Round basket' },
          { value: 'rect', label: 'Rectangular' },
        ],
      },
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.3,
        max: 0.6,
        step: 0.05,
        default: 0.4,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.3,
        max: 0.6,
        step: 0.05,
        default: 0.4,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.22,
        max: 0.45,
        step: 0.02,
        default: 0.32,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Weave', default: '#b8a382' },
      {
        kind: 'enum',
        key: 'lid',
        label: 'Lid',
        default: 'no',
        options: [
          { value: 'no', label: 'Open' },
          { value: 'yes', label: 'With lid' },
        ],
      },
    ],
  },
  // ============================================================================
  // 2b. Cat set
  // ============================================================================
  'cat-tree': {
    kind: 'parametric',
    id: 'cat-tree',
    name: 'Cat tree',
    keywords: ['cat', 'cat tree', 'condo', 'tower', 'climbing', 'scratching', 'perch', 'sisal'],
    category: 'pets',
    primitive: 'CatTree',
    defaultFootprint: { w: 0.5, d: 0.5, h: 1.4 },
    footprintParams: { w: 'baseWidth', d: 'baseWidth' },
    verticalSpan: { base: 0, top: 1.8 },
    paramSchema: [
      { kind: 'integer', key: 'tiers', label: 'Tiers', min: 2, max: 5, default: 3 },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.9,
        max: 1.8,
        step: 0.05,
        default: 1.4,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'baseWidth',
        label: 'Base width',
        min: 0.4,
        max: 0.6,
        step: 0.05,
        default: 0.5,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'postStyle',
        label: 'Posts',
        default: 'sisal',
        options: [
          { value: 'sisal', label: 'Sisal rope' },
          { value: 'ribbed', label: 'Ribbed' },
        ],
      },
      {
        kind: 'enum',
        key: 'house',
        label: 'House cube',
        default: 'yes',
        options: [
          { value: 'yes', label: 'Include' },
          { value: 'no', label: 'None' },
        ],
      },
      {
        kind: 'enum',
        key: 'topPerch',
        label: 'Top perch',
        default: 'yes',
        options: [
          { value: 'yes', label: 'Include' },
          { value: 'no', label: 'None' },
        ],
      },
      { kind: 'color', key: 'plushColor', label: 'Plush', default: '#c8bda8' },
      { kind: 'color', key: 'postColor', label: 'Rope', default: '#c9a875' },
    ],
  },
  'cat-wall-shelf': {
    kind: 'parametric',
    id: 'cat-wall-shelf',
    name: 'Cat wall shelf',
    keywords: ['cat', 'wall shelf', 'ledge', 'climbing', 'perch', 'mounted'],
    category: 'pets',
    primitive: 'CatWallShelf',
    defaultFootprint: { w: 0.5, d: 0.28, h: 0.1 },
    footprintParams: { w: 'width', d: 'depth' },
    mounted: true,
    verticalSpan: { base: 1.2, top: 1.42 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.35,
        max: 0.9,
        step: 0.05,
        default: 0.5,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.25,
        max: 0.3,
        step: 0.01,
        default: 0.28,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 0.6,
        max: 2.2,
        step: 0.05,
        default: 1.3,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#8a6b48' },
      { kind: 'color', key: 'plushColor', label: 'Grip pad', default: '#c8bda8' },
    ],
  },
  'cat-wall-steps': {
    kind: 'parametric',
    id: 'cat-wall-steps',
    name: 'Cat wall steps',
    keywords: ['cat', 'steps', 'stairs', 'climbing', 'wall', 'mounted', 'diagonal'],
    category: 'pets',
    primitive: 'CatWallSteps',
    // True default extent: run·(count−1) + stepWidth = 0.4·3 + 0.34. The formula
    // isn't expressible via `footprintParams` (1:1 numeric mapping only), so
    // wider non-default runs aren't collision-tracked — acceptable for a
    // wall-mounted fixture (mounted role, off the walkable floor).
    defaultFootprint: { w: 1.54, d: 0.26, h: 1.0 },
    mounted: true,
    verticalSpan: { base: 0.85, top: 1.85 },
    paramSchema: [
      { kind: 'integer', key: 'count', label: 'Steps', min: 3, max: 5, default: 4 },
      {
        kind: 'number',
        key: 'rise',
        label: 'Rise',
        min: 0.18,
        max: 0.38,
        step: 0.02,
        default: 0.28,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'run',
        label: 'Run',
        min: 0.3,
        max: 0.55,
        step: 0.05,
        default: 0.4,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'stepWidth',
        label: 'Step width',
        min: 0.28,
        max: 0.45,
        step: 0.01,
        default: 0.34,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'First step',
        min: 0.4,
        max: 1.2,
        step: 0.05,
        default: 0.9,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#8a6b48' },
      { kind: 'color', key: 'plushColor', label: 'Grip pad', default: '#c8bda8' },
    ],
  },
  'cat-wall-bridge': {
    kind: 'parametric',
    id: 'cat-wall-bridge',
    name: 'Cat wall bridge',
    keywords: ['cat', 'bridge', 'catwalk', 'span', 'wall', 'mounted', 'slats'],
    category: 'pets',
    primitive: 'CatWallBridge',
    defaultFootprint: { w: 1.2, d: 0.26, h: 0.1 },
    footprintParams: { w: 'span', d: 'depth' },
    mounted: true,
    verticalSpan: { base: 1.5, top: 1.72 },
    paramSchema: [
      {
        kind: 'number',
        key: 'span',
        label: 'Span',
        min: 0.8,
        max: 2.0,
        step: 0.1,
        default: 1.2,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.22,
        max: 0.3,
        step: 0.02,
        default: 0.26,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'mountHeight',
        label: 'Mount height',
        min: 0.8,
        max: 2.2,
        step: 0.05,
        default: 1.6,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#8a6b48' },
      { kind: 'color', key: 'plushColor', label: 'Treads', default: '#c8bda8' },
    ],
  },
  'scratching-post': {
    kind: 'parametric',
    id: 'scratching-post',
    name: 'Scratching post',
    keywords: ['cat', 'scratcher', 'scratching post', 'sisal', 'pad'],
    category: 'pets',
    primitive: 'ScratchingPost',
    defaultFootprint: { w: 0.44, d: 0.44, h: 0.74 },
    verticalSpan: { base: 0, top: 0.82 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'vertical',
        options: [
          { value: 'vertical', label: 'Vertical post' },
          { value: 'angled', label: 'Angled board' },
          { value: 'pad', label: 'Floor pad' },
        ],
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.4,
        max: 0.9,
        step: 0.05,
        default: 0.7,
        unit: 'm',
      },
      { kind: 'color', key: 'sisalColor', label: 'Sisal', default: '#c9a875' },
      { kind: 'color', key: 'baseColor', label: 'Base', default: '#c8bda8' },
    ],
  },
  'litter-box': {
    kind: 'parametric',
    id: 'litter-box',
    name: 'Litter box',
    keywords: ['cat', 'litter', 'litter box', 'tray', 'toilet', 'covered'],
    category: 'pets',
    primitive: 'LitterBox',
    defaultFootprint: { w: 0.56, d: 0.46, h: 0.41 },
    // Clear floor in front so the entry is reachable (covered/top-entry access).
    frontClearance: 0.5,
    paramSchema: [
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'covered',
        options: [
          { value: 'open', label: 'Open tray' },
          { value: 'covered', label: 'Covered hood' },
          { value: 'top-entry', label: 'Top entry' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Colour', default: '#5a6b74' },
    ],
  },
  'litter-cabinet': {
    kind: 'parametric',
    id: 'litter-cabinet',
    name: 'Litter cabinet',
    keywords: ['cat', 'litter', 'cabinet', 'enclosure', 'concealment', 'bench', 'furniture'],
    category: 'pets',
    primitive: 'LitterCabinet',
    defaultFootprint: { w: 0.72, d: 0.52, h: 0.5 },
    footprintParams: { w: 'width', d: 'depth' },
    frontClearance: 0.4,
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.65,
        max: 1.0,
        step: 0.05,
        default: 0.72,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.5,
        max: 0.65,
        step: 0.05,
        default: 0.52,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.45,
        max: 0.6,
        step: 0.05,
        default: 0.5,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'entrySide',
        label: 'Entry side',
        default: 'left',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'right', label: 'Right' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#9d7c54' },
    ],
  },
  'cat-window-perch': {
    kind: 'parametric',
    id: 'cat-window-perch',
    name: 'Cat window perch',
    keywords: ['cat', 'window', 'perch', 'sill', 'lounger', 'sunbathe'],
    category: 'pets',
    primitive: 'CatWindowPerch',
    defaultFootprint: { w: 0.7, d: 0.35, h: 0.35 },
    // Sits at the sill of a window; never blocks floor placement.
    noClip: true,
    // Window-bound: snaps to the nearest window and sits at sill height.
    windowBound: true,
    paramSchema: [
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.28,
        max: 0.42,
        step: 0.02,
        default: 0.32,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#8a6b48' },
      { kind: 'color', key: 'plushColor', label: 'Cushion', default: '#c8bda8' },
    ],
  },
  'cat-tunnel': {
    kind: 'parametric',
    id: 'cat-tunnel',
    name: 'Cat tunnel',
    keywords: ['cat', 'tunnel', 'tube', 'play', 'hideaway'],
    category: 'pets',
    primitive: 'CatTunnel',
    defaultFootprint: { w: 1.0, d: 0.3, h: 0.3 },
    footprintParams: { w: 'length', d: 'diameter' },
    verticalSpan: { base: 0, top: 0.32 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'straight',
        options: [
          { value: 'straight', label: 'Straight' },
          { value: 's-curve', label: 'S-curve' },
        ],
      },
      {
        kind: 'number',
        key: 'length',
        label: 'Length',
        min: 0.7,
        max: 1.6,
        step: 0.1,
        default: 1.0,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'diameter',
        label: 'Diameter',
        min: 0.24,
        max: 0.36,
        step: 0.02,
        default: 0.3,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Fabric', default: '#7f8a94' },
    ],
  },
  // ============================================================================
  // 2c. Birds
  // ============================================================================
  'bird-cage': {
    kind: 'parametric',
    id: 'bird-cage',
    name: 'Bird cage',
    keywords: ['bird', 'cage', 'aviary', 'parrot', 'budgie', 'canary', 'perch'],
    category: 'pets',
    primitive: 'BirdCage',
    // Footprint matches the default (M) size; the `size` enum drives live dims.
    defaultFootprint: { w: 0.56, d: 0.56, h: 1.44 },
    verticalSpan: { base: 0, top: 1.5 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'size',
        label: 'Size',
        default: 'M',
        options: [
          { value: 'S', label: 'Small' },
          { value: 'M', label: 'Medium' },
        ],
      },
      {
        kind: 'enum',
        key: 'mount',
        label: 'Mount',
        default: 'stand',
        options: [
          { value: 'stand', label: 'On stand' },
          { value: 'tabletop', label: 'Tabletop' },
        ],
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Cage shape',
        default: 'dome',
        options: [
          { value: 'dome', label: 'Dome (round)' },
          { value: 'rect', label: 'Rectangular' },
        ],
      },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#3a3d42' },
    ],
  },
  'bird-play-gym': {
    kind: 'parametric',
    id: 'bird-play-gym',
    name: 'Bird play gym',
    keywords: ['bird', 'play gym', 'playstand', 'perch', 'ladder', 'parrot'],
    category: 'pets',
    primitive: 'BirdPlayGym',
    defaultFootprint: { w: 0.42, d: 0.28, h: 0.43 },
    verticalSpan: { base: 0, top: 0.45 },
    paramSchema: [
      { kind: 'color', key: 'color', label: 'Perch (wood)', default: '#b98f5e' },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#3a3d42' },
    ],
  },
  // ============================================================================
  // 2d. Small pets (rabbits, guinea pigs, hamsters)
  // ============================================================================
  'rabbit-hutch': {
    kind: 'parametric',
    id: 'rabbit-hutch',
    name: 'Rabbit hutch',
    keywords: ['rabbit', 'small-pet', 'hutch', 'bunny', 'cage', 'run', 'guinea pig'],
    category: 'pets',
    primitive: 'RabbitHutch',
    defaultFootprint: { w: 1.35, d: 0.6, h: 0.9 },
    footprintParams: { w: 'width', d: 'depth' },
    frontClearance: 0.4,
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.9,
        max: 1.6,
        step: 0.05,
        default: 1.35,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.5,
        max: 0.75,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.7,
        max: 1.1,
        step: 0.05,
        default: 0.9,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Timber', default: '#9d7c54' },
      { kind: 'color', key: 'wireColor', label: 'Wire', default: '#5b6068' },
    ],
  },
  'small-pet-pen': {
    kind: 'parametric',
    id: 'small-pet-pen',
    name: 'Small-pet pen',
    keywords: ['guinea-pig', 'guinea pig', 'small-pet', 'pen', 'C&C', 'grid', 'cage', 'rabbit'],
    category: 'pets',
    primitive: 'SmallPetPen',
    // 3×2 grids × 0.36 m cell (≈41×27 in), the C&C minimum for a pair. The grid
    // count drives live dims in the primitive; the footprint stays the default
    // bbox (grid counts aren't metres, so they can't feed footprintParams).
    defaultFootprint: { w: 1.08, d: 0.72, h: 0.36 },
    frontClearance: 0.4,
    paramSchema: [
      { kind: 'integer', key: 'gridsX', label: 'Grids across', min: 2, max: 6, default: 3 },
      { kind: 'integer', key: 'gridsY', label: 'Grids deep', min: 2, max: 6, default: 2 },
      { kind: 'color', key: 'wireColor', label: 'Grid', default: '#e8ebee' },
      { kind: 'color', key: 'baseColor', label: 'Coroplast base', default: '#6b8fb0' },
    ],
  },
  'hamster-tank': {
    kind: 'parametric',
    id: 'hamster-tank',
    name: 'Hamster enclosure',
    keywords: ['hamster', 'small-pet', 'tank', 'bin cage', 'gerbil', 'glass', 'terrarium'],
    category: 'pets',
    primitive: 'HamsterTank',
    // Footprint matches the default (M) size on the floor; `size`/`base` drive dims.
    defaultFootprint: { w: 1.0, d: 0.5, h: 0.45 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'size',
        label: 'Size',
        default: 'M',
        options: [
          { value: 'S', label: 'Small (80 cm)' },
          { value: 'M', label: 'Medium (100 cm)' },
        ],
      },
      {
        kind: 'enum',
        key: 'base',
        label: 'Base',
        default: 'floor',
        options: [
          { value: 'floor', label: 'On floor' },
          { value: 'stand', label: 'On stand' },
        ],
      },
      { kind: 'color', key: 'beddingColor', label: 'Bedding', default: '#d8c39a' },
      { kind: 'color', key: 'glassColor', label: 'Glass', default: '#cfe0e6' },
      { kind: 'color', key: 'frameColor', label: 'Frame', default: '#1b1b1e' },
    ],
  },
  // ============================================================================
  // 2e. Fish
  // ============================================================================
  'aquarium-stand': {
    kind: 'parametric',
    id: 'aquarium-stand',
    name: 'Aquarium stand + tank',
    keywords: ['fish', 'aquarium', 'tank', 'stand', 'cabinet', 'fish tank', 'water'],
    category: 'pets',
    primitive: 'AquariumStand',
    // `tankLength` (enum) drives live dims; enums can't feed `footprintParams`,
    // so the footprint is pinned to the LARGEST (1.2 m) tank — conservative
    // over-report for smaller tanks, never an under-report (a ~300 kg appliance
    // must not clip walls/neighbours).
    defaultFootprint: { w: 1.2, d: 0.5, h: 1.25 },
    verticalSpan: { base: 0, top: 1.3 },
    // Load rating surfaced descriptively (LP4): a filled tank is very heavy.
    description:
      'A water-filled tank is heavy — a 1.2 m tank runs ~300 kg. The steel frame is load-rated; place it against a wall on solid, level flooring.',
    paramSchema: [
      {
        kind: 'enum',
        key: 'tankLength',
        label: 'Tank length',
        default: '0.9',
        options: [
          { value: '0.6', label: '0.6 m (~60 L)' },
          { value: '0.9', label: '0.9 m (~150 L)' },
          { value: '1.2', label: '1.2 m (~250 L)' },
        ],
      },
      {
        kind: 'enum',
        key: 'doors',
        label: 'Cabinet doors',
        default: 'yes',
        options: [
          { value: 'yes', label: 'Doors' },
          { value: 'no', label: 'Open shelf' },
        ],
      },
      { kind: 'color', key: 'frameColor', label: 'Steel frame', default: '#2b2d31' },
      {
        kind: 'enum',
        key: 'cabinetFinish',
        label: 'Cabinet finish',
        default: 'painted',
        options: [
          { value: 'painted', label: 'Painted MDF' },
          { value: 'wood', label: 'Wood' },
        ],
      },
      { kind: 'color', key: 'cabinetColor', label: 'Cabinet', default: '#3a3f45' },
      { kind: 'color', key: 'waterColor', label: 'Water tint', default: '#3f7d8c' },
    ],
  },
} satisfies Record<string, FurnitureDef>
