import { RECLINER_BBOX_DEPTH, RECLINER_EXTENT } from '../primitives/Recliner'
import { SOFA_BED_DEPTH } from '../primitives/SofaBed'
import type { FurnitureDef } from '../types'

/** seating furniture definitions. Part of the built-in catalog (see ../builtinCatalog.ts). */
export const SEATING_DEFS = {
  // ── Seating ─────────────────────────────────────────────────────────────
  'sofa-3seat': {
    kind: 'parametric',
    id: 'sofa-3seat',
    name: '3-seat sofa',
    category: 'seating',
    keywords: ['couch', 'settee', 'lounge'],
    primitive: 'Sofa',
    defaultFootprint: { w: 2.1, d: 0.9, h: 0.85 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 1.8,
        max: 2.4,
        step: 0.05,
        default: 2.1,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.85,
        max: 1.0,
        step: 0.05,
        default: 0.9,
        unit: 'm',
      },
      { kind: 'integer', key: 'cushionCount', label: 'Cushions', min: 2, max: 4, default: 3 },
      { kind: 'color', key: 'color', label: 'Upholstery', default: '#8aa1a8' },
      {
        kind: 'enum',
        key: 'material',
        label: 'Material',
        default: 'fabric',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'leather', label: 'Leather' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      {
        kind: 'enum',
        key: 'armStyle',
        label: 'Arms',
        default: 'standard',
        options: [
          { value: 'standard', label: 'Standard' },
          { value: 'low', label: 'Low' },
          { value: 'armless', label: 'Armless' },
        ],
      },
      { kind: 'color', key: 'pillowColor', label: 'Throw pillows', default: '#c8775c' },
      {
        kind: 'enum',
        key: 'accentPillows',
        label: 'Pillows',
        default: 'two',
        options: [
          { value: 'none', label: 'None' },
          { value: 'two', label: 'Two' },
          { value: 'four', label: 'Four' },
        ],
      },
      {
        kind: 'enum',
        key: 'pillowPattern',
        label: 'Pillow weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'sofa-2seat': {
    kind: 'parametric',
    id: 'sofa-2seat',
    name: '2-seat sofa',
    category: 'seating',
    keywords: ['couch', 'settee', 'loveseat'],
    primitive: 'Sofa',
    defaultFootprint: { w: 1.5, d: 0.9, h: 0.85 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 1.3,
        max: 1.7,
        step: 0.05,
        default: 1.5,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.85,
        max: 1.0,
        step: 0.05,
        default: 0.9,
        unit: 'm',
      },
      { kind: 'integer', key: 'cushionCount', label: 'Cushions', min: 2, max: 3, default: 2 },
      { kind: 'color', key: 'color', label: 'Upholstery', default: '#8aa1a8' },
      {
        kind: 'enum',
        key: 'material',
        label: 'Material',
        default: 'fabric',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'leather', label: 'Leather' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      {
        kind: 'enum',
        key: 'armStyle',
        label: 'Arms',
        default: 'standard',
        options: [
          { value: 'standard', label: 'Standard' },
          { value: 'low', label: 'Low' },
          { value: 'armless', label: 'Armless' },
        ],
      },
      { kind: 'color', key: 'pillowColor', label: 'Throw pillows', default: '#c8775c' },
      {
        kind: 'enum',
        key: 'accentPillows',
        label: 'Pillows',
        default: 'two',
        options: [
          { value: 'none', label: 'None' },
          { value: 'two', label: 'Two' },
          { value: 'four', label: 'Four' },
        ],
      },
      {
        kind: 'enum',
        key: 'pillowPattern',
        label: 'Pillow weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'sofa-lshape': {
    kind: 'parametric',
    id: 'sofa-lshape',
    name: 'L-shaped sectional',
    category: 'seating',
    primitive: 'SofaSectional',
    defaultFootprint: { w: 2.5, d: 1.95, h: 0.85 },
    // Granular footprint: the main run + the perpendicular chaise, leaving the
    // concave notch (forward of the non-chaise side) open — so a piece can sit
    // in the L instead of being blocked by the full bounding box. Matches the
    // SofaSectional primitive's geometry (footprint centred; back faces −Z).
    footprintParts: (props) => {
      const width = typeof props.width === 'number' ? props.width : 2.5
      const depth = typeof props.depth === 'number' ? props.depth : 0.95
      const chaise = typeof props.chaise === 'number' ? props.chaise : 1.0
      const side = props.chaiseSide === 'left' ? -1 : 1
      const chaiseW = depth // square-ish chaise, matching the primitive
      return [
        // Main run: full width along the back, one depth deep.
        { dx: 0, dz: -chaise / 2, w: width, d: depth },
        // Chaise return: forward of the main seat on `chaiseSide`.
        { dx: side * (width / 2 - chaiseW / 2), dz: depth / 2, w: chaiseW, d: chaise },
      ]
    },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Main width',
        min: 2.0,
        max: 3.0,
        step: 0.1,
        default: 2.5,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.9,
        max: 1.05,
        step: 0.05,
        default: 0.95,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'chaise',
        label: 'Chaise',
        min: 0.7,
        max: 1.4,
        step: 0.05,
        default: 1.0,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'chaiseSide',
        label: 'Chaise side',
        default: 'right',
        options: [
          { value: 'right', label: 'Right' },
          { value: 'left', label: 'Left' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Upholstery', default: '#8a9098' },
      {
        kind: 'enum',
        key: 'material',
        label: 'Material',
        default: 'fabric',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'leather', label: 'Leather' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'color', key: 'pillowColor', label: 'Throw pillows', default: '#b5683f' },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'dining-chair': {
    kind: 'parametric',
    id: 'dining-chair',
    name: 'Dining chair',
    keywords: ['kitchen chair'],
    category: 'seating',
    primitive: 'DiningChair',
    defaultFootprint: { w: 0.46, d: 0.48, h: 0.92 },
    paramSchema: [
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'upholstered', label: 'Upholstered' },
        ],
      },
      { kind: 'color', key: 'seatColor', label: 'Seat', default: '#7a5c3c' },
      { kind: 'color', key: 'legColor', label: 'Legs', default: '#4e3a24' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Seat finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Weave (upholstered)',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'office-chair': {
    kind: 'parametric',
    id: 'office-chair',
    name: 'Office chair',
    keywords: ['desk chair', 'task chair', 'swivel chair', 'gaming chair'],
    category: 'seating',
    primitive: 'OfficeChair',
    defaultFootprint: { w: 0.6, d: 0.6, h: 1.0 },
    paramSchema: [
      { kind: 'color', key: 'color', label: 'Upholstery', default: '#2b2f33' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'task',
        options: [
          { value: 'task', label: 'Task' },
          { value: 'executive', label: 'Executive' },
          { value: 'mesh', label: 'Mesh back' },
          { value: 'gaming', label: 'Gaming' },
        ],
      },
      {
        kind: 'enum',
        key: 'material',
        label: 'Material',
        default: 'fabric',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'leather', label: 'Leather' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'bar-stool': {
    kind: 'parametric',
    id: 'bar-stool',
    name: 'Bar stool',
    keywords: [
      'counter stool',
      'high stool',
      'breakfast stool',
      'step stool',
      'kitchen stool',
      'stepladder',
    ],
    category: 'seating',
    primitive: 'BarStool',
    defaultFootprint: { w: 0.42, d: 0.42, h: 0.71 },
    paramSchema: [
      { kind: 'color', key: 'seatColor', label: 'Seat', default: '#7a5c3c' },
      { kind: 'color', key: 'legColor', label: 'Legs', default: '#3a3d42' },
      {
        // Order keeps the multi-part modes within the structural harness's
        // auto-covered default + first 3 extras; 'pedestal' (unchanged from the
        // Wave-1A audit, a solidly-connected column-on-disc) is the mode left
        // out of the auto-sample.
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'splayed',
        options: [
          { value: 'splayed', label: 'Splayed legs' },
          { value: 'backed', label: 'With backrest' },
          { value: 'step', label: 'Step stool' },
          { value: 'kitchen', label: 'Kitchen stool' },
          { value: 'pedestal', label: 'Pedestal base' },
        ],
      },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Seat finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  bench: {
    kind: 'parametric',
    id: 'bench',
    name: 'Bench',
    category: 'seating',
    primitive: 'Bench',
    defaultFootprint: { w: 1.2, d: 0.4, h: 0.45 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.8,
        max: 1.8,
        step: 0.05,
        default: 1.2,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.3,
        max: 0.5,
        step: 0.02,
        default: 0.4,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'upholstered',
        options: [
          { value: 'upholstered', label: 'Upholstered' },
          { value: 'storage', label: 'Storage ottoman' },
          { value: 'slat', label: 'Wood slat' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Top', default: '#b08968' },
      { kind: 'color', key: 'legColor', label: 'Legs', default: '#3a2c1d' },
      {
        kind: 'enum',
        key: 'material',
        label: 'Material',
        default: 'fabric',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'leather', label: 'Leather' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  armchair: {
    kind: 'parametric',
    id: 'armchair',
    name: 'Armchair',
    keywords: [
      'accent chair',
      'lounge chair',
      'easy chair',
      'occasional chair',
      'swivel chair',
      'tub chair',
    ],
    category: 'seating',
    primitive: 'Armchair',
    defaultFootprint: { w: 0.85, d: 0.85, h: 0.92 },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.7,
        max: 1.0,
        step: 0.05,
        default: 0.85,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.7,
        max: 0.95,
        step: 0.05,
        default: 0.85,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Upholstery', default: '#b06a52' },
      {
        kind: 'enum',
        key: 'style',
        label: 'Style',
        default: 'standard',
        options: [
          { value: 'standard', label: 'Lounge' },
          { value: 'wingback', label: 'Wingback' },
          { value: 'tub', label: 'Tub / barrel' },
          { value: 'swivel', label: 'Swivel tub' },
        ],
      },
      {
        kind: 'enum',
        key: 'material',
        label: 'Material',
        default: 'fabric',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'leather', label: 'Leather' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  ottoman: {
    kind: 'parametric',
    id: 'ottoman',
    name: 'Ottoman / pouf',
    category: 'seating',
    keywords: ['pouf', 'pouffe', 'footstool', 'footrest'],
    primitive: 'Ottoman',
    defaultFootprint: { w: 0.6, d: 0.6, h: 0.42 },
    footprintParams: { w: 'width', d: 'depth' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.4,
        max: 1.1,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Depth',
        min: 0.4,
        max: 0.7,
        step: 0.05,
        default: 0.6,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'height',
        label: 'Height',
        min: 0.32,
        max: 0.5,
        step: 0.02,
        default: 0.42,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'shape',
        label: 'Shape',
        default: 'round',
        options: [
          { value: 'round', label: 'Round drum' },
          { value: 'square', label: 'Square cube' },
          { value: 'rect', label: 'Rectangle' },
          { value: 'pouffe', label: 'Knitted pouffe' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Upholstery', default: '#b9683f' },
      {
        kind: 'enum',
        key: 'material',
        label: 'Material',
        default: 'fabric',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'leather', label: 'Leather' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      {
        kind: 'enum',
        key: 'tufting',
        label: 'Tufting',
        default: 'none',
        options: [
          { value: 'none', label: 'Smooth' },
          { value: 'buttons', label: 'Buttoned' },
        ],
      },
      {
        kind: 'enum',
        key: 'feet',
        label: 'Feet',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood feet' },
          { value: 'none', label: 'Flush' },
        ],
      },
      { kind: 'color', key: 'legColor', label: 'Feet', default: '#3a2c1d' },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'chaise-lounge': {
    kind: 'parametric',
    id: 'chaise-lounge',
    name: 'Chaise lounge',
    category: 'seating',
    keywords: ['daybed', 'recliner', 'lounger', 'chaise'],
    primitive: 'ChaiseLounge',
    defaultFootprint: { w: 0.72, d: 1.75, h: 0.85 },
    footprintParams: { w: 'depth', d: 'width' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Length',
        min: 1.5,
        max: 2.0,
        step: 0.05,
        default: 1.75,
        unit: 'm',
      },
      {
        kind: 'number',
        key: 'depth',
        label: 'Seat width',
        min: 0.6,
        max: 0.85,
        step: 0.02,
        default: 0.72,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Upholstery', default: '#8a9aa0' },
      {
        kind: 'enum',
        key: 'material',
        label: 'Material',
        default: 'fabric',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'leather', label: 'Leather' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      {
        kind: 'enum',
        key: 'arm',
        label: 'Arm',
        default: 'one',
        options: [
          { value: 'one', label: 'One side' },
          { value: 'none', label: 'None' },
        ],
      },
      { kind: 'color', key: 'legColor', label: 'Legs', default: '#3a2c1d' },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'sofa-bed': {
    kind: 'parametric',
    id: 'sofa-bed',
    name: 'Sofa bed',
    category: 'seating',
    keywords: ['sofa bed', 'sleeper', 'futon', 'daybed', 'guest bed', 'click-clack', 'convertible'],
    primitive: 'SofaBed',
    // Bbox depth = the deeper BED mode (the enclosing bbox must cover every
    // footprintParts box); the shallower sofa depth is served per-mode below.
    defaultFootprint: { w: 1.9, d: SOFA_BED_DEPTH.bed, h: 0.85 },
    // Honest per-mode footprint (sofa-lshape / wardrobe-corner precedent): the
    // piece's back (wall) edge is pinned at −bboxDepth/2, so it only grows
    // FORWARD into the room when unfolded to `bed`. `mode` is an enum (can't
    // feed footprintParams), so a props-driven footprintParts serves each mode
    // its true depth rather than pinning every mode to the deepest box.
    footprintParts: (props) => {
      const width = typeof props.width === 'number' ? props.width : 1.9
      const mode = typeof props.mode === 'string' ? props.mode : 'sofa'
      const bboxDepth = SOFA_BED_DEPTH.bed
      const pieceDepth = SOFA_BED_DEPTH[mode] ?? SOFA_BED_DEPTH.sofa
      const backZ = -bboxDepth / 2
      return [{ dx: 0, dz: backZ + pieceDepth / 2, w: width, d: pieceDepth }]
    },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 1.7,
        max: 2.1,
        step: 0.05,
        default: 1.9,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'mode',
        label: 'Mode',
        default: 'sofa',
        options: [
          { value: 'sofa', label: 'Sofa' },
          { value: 'bed', label: 'Fold-out bed' },
        ],
      },
      {
        kind: 'enum',
        key: 'storage',
        label: 'Under-seat storage',
        default: 'yes',
        options: [
          { value: 'yes', label: 'Drawer' },
          { value: 'no', label: 'None' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Upholstery', default: '#6f7a82' },
      {
        kind: 'enum',
        key: 'material',
        label: 'Material',
        default: 'fabric',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'leather', label: 'Leather' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'color', key: 'pillowColor', label: 'Throw pillows', default: '#b8836a' },
      { kind: 'color', key: 'legColor', label: 'Legs', default: '#2c2620' },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  'bay-daybed': {
    kind: 'parametric',
    id: 'bay-daybed',
    name: 'Bay-window daybed',
    category: 'seating',
    keywords: [
      'daybed',
      'window bench',
      'window seat',
      'bay window',
      'reading bench',
      'window daybed',
    ],
    primitive: 'BayDaybed',
    // Freestanding (NOT windowBound) — ordinary furniture placed near a window.
    // Depth fixed at 0.6 m; width is numeric so the footprint tracks it.
    defaultFootprint: { w: 1.7, d: 0.6, h: 0.45 },
    footprintParams: { w: 'width' },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 1.4,
        max: 2.0,
        step: 0.05,
        default: 1.7,
        unit: 'm',
      },
      { kind: 'color', key: 'color', label: 'Cushion', default: '#9aa7ad' },
      {
        kind: 'enum',
        key: 'material',
        label: 'Cushion fabric',
        default: 'fabric',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'velvet', label: 'Velvet' },
          { value: 'leather', label: 'Leather' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
        ],
      },
      { kind: 'color', key: 'bolsterColor', label: 'Bolsters', default: '#c2a98a' },
      { kind: 'color', key: 'baseColor', label: 'Base', default: '#7a6647' },
      {
        kind: 'enum',
        key: 'finish',
        label: 'Base finish',
        default: 'wood',
        options: [
          { value: 'wood', label: 'Wood' },
          { value: 'painted', label: 'Painted' },
          { value: 'gloss', label: 'Gloss' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
  recliner: {
    kind: 'parametric',
    id: 'recliner',
    name: 'Recliner armchair',
    category: 'seating',
    keywords: ['reclining chair', 'lazy chair', 'lounge chair', 'armchair', 'footrest', 'la-z-boy'],
    primitive: 'Recliner',
    // Bbox depth = the deep `reclined` state (footrest fully out); the shallower
    // upright depth is served per-mode below. The wall (back) edge is pinned so
    // the piece only grows FORWARD into the room when it reclines.
    defaultFootprint: { w: 0.85, d: RECLINER_BBOX_DEPTH, h: 1.05 },
    // Honest per-mode footprint (sofa-bed precedent): `position` is an enum (can't
    // feed footprintParams), so a props-driven footprintParts serves each mode its
    // true [rear, front] extent. The primitive is built back-pinned at
    // −RECLINER_BBOX_DEPTH/2, so upright reports a shallower box than reclined.
    footprintParts: (props) => {
      const width = typeof props.width === 'number' ? props.width : 0.85
      const position = typeof props.position === 'string' ? props.position : 'upright'
      const ext = RECLINER_EXTENT[position] ?? RECLINER_EXTENT.upright
      return [{ dx: 0, dz: (ext.rear + ext.front) / 2, w: width, d: ext.front - ext.rear }]
    },
    paramSchema: [
      {
        kind: 'number',
        key: 'width',
        label: 'Width',
        min: 0.75,
        max: 0.95,
        step: 0.05,
        default: 0.85,
        unit: 'm',
      },
      {
        kind: 'enum',
        key: 'position',
        label: 'Position',
        default: 'upright',
        options: [
          { value: 'upright', label: 'Upright' },
          { value: 'reclined', label: 'Reclined' },
        ],
      },
      { kind: 'color', key: 'color', label: 'Upholstery', default: '#6b5747' },
      {
        kind: 'enum',
        key: 'material',
        label: 'Material',
        default: 'leather',
        options: [
          { value: 'fabric', label: 'Fabric' },
          { value: 'leather', label: 'Leather' },
          { value: 'velvet', label: 'Velvet' },
        ],
      },
      {
        kind: 'enum',
        key: 'pattern',
        label: 'Weave',
        default: 'plain',
        options: [
          { value: 'plain', label: 'Plain' },
          { value: 'striped', label: 'Striped' },
          { value: 'herringbone', label: 'Herringbone' },
          { value: 'checkered', label: 'Checkered' },
          { value: 'plaid', label: 'Plaid' },
          { value: 'dots', label: 'Dots' },
        ],
      },
      { kind: 'number', key: 'sheen', label: 'Sheen', min: 0, max: 1, step: 0.05, default: 0 },
    ],
  },
} satisfies Record<string, FurnitureDef>
